// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/kit/kit.proto

package kit

import (
	fmt "fmt"
	node "github.com/cloudproud/lunodb.pb/proto/kit/node"
	plan "github.com/cloudproud/lunodb.pb/proto/kit/plan"
	types "github.com/cloudproud/lunodb.pb/proto/kit/types"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ConnectorResponse struct {
	// Types that are valid to be assigned to State:
	//
	//	*ConnectorResponse_Ping
	//	*ConnectorResponse_Fetch
	//	*ConnectorResponse_ExecuteStatement
	State                isConnectorResponse_State `protobuf_oneof:"state"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ConnectorResponse) Reset()         { *m = ConnectorResponse{} }
func (m *ConnectorResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectorResponse) ProtoMessage()    {}
func (*ConnectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{1}
}
func (m *ConnectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectorResponse.Unmarshal(m, b)
}
func (m *ConnectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectorResponse.Marshal(b, m, deterministic)
}
func (m *ConnectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectorResponse.Merge(m, src)
}
func (m *ConnectorResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectorResponse.Size(m)
}
func (m *ConnectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectorResponse proto.InternalMessageInfo

type isConnectorResponse_State interface {
	isConnectorResponse_State()
}

type ConnectorResponse_Ping struct {
	Ping *PingResponse `protobuf:"bytes,1,opt,name=ping,proto3,oneof" json:"ping,omitempty"`
}
type ConnectorResponse_Fetch struct {
	Fetch *FetchResponse `protobuf:"bytes,2,opt,name=fetch,proto3,oneof" json:"fetch,omitempty"`
}
type ConnectorResponse_ExecuteStatement struct {
	ExecuteStatement *ExecuteStatementResponse `protobuf:"bytes,3,opt,name=execute_statement,json=executeStatement,proto3,oneof" json:"execute_statement,omitempty"`
}

func (*ConnectorResponse_Ping) isConnectorResponse_State()             {}
func (*ConnectorResponse_Fetch) isConnectorResponse_State()            {}
func (*ConnectorResponse_ExecuteStatement) isConnectorResponse_State() {}

func (m *ConnectorResponse) GetState() isConnectorResponse_State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ConnectorResponse) GetPing() *PingResponse {
	if x, ok := m.GetState().(*ConnectorResponse_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *ConnectorResponse) GetFetch() *FetchResponse {
	if x, ok := m.GetState().(*ConnectorResponse_Fetch); ok {
		return x.Fetch
	}
	return nil
}

func (m *ConnectorResponse) GetExecuteStatement() *ExecuteStatementResponse {
	if x, ok := m.GetState().(*ConnectorResponse_ExecuteStatement); ok {
		return x.ExecuteStatement
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConnectorResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConnectorResponse_Ping)(nil),
		(*ConnectorResponse_Fetch)(nil),
		(*ConnectorResponse_ExecuteStatement)(nil),
	}
}

type ConnectorRequest struct {
	// Types that are valid to be assigned to State:
	//
	//	*ConnectorRequest_Ping
	//	*ConnectorRequest_Fetch
	//	*ConnectorRequest_ExecuteStatement
	State                isConnectorRequest_State `protobuf_oneof:"state"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *ConnectorRequest) Reset()         { *m = ConnectorRequest{} }
func (m *ConnectorRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectorRequest) ProtoMessage()    {}
func (*ConnectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{2}
}
func (m *ConnectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectorRequest.Unmarshal(m, b)
}
func (m *ConnectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectorRequest.Marshal(b, m, deterministic)
}
func (m *ConnectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectorRequest.Merge(m, src)
}
func (m *ConnectorRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectorRequest.Size(m)
}
func (m *ConnectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectorRequest proto.InternalMessageInfo

type isConnectorRequest_State interface {
	isConnectorRequest_State()
}

type ConnectorRequest_Ping struct {
	Ping *PingRequest `protobuf:"bytes,1,opt,name=ping,proto3,oneof" json:"ping,omitempty"`
}
type ConnectorRequest_Fetch struct {
	Fetch *FetchRequest `protobuf:"bytes,2,opt,name=fetch,proto3,oneof" json:"fetch,omitempty"`
}
type ConnectorRequest_ExecuteStatement struct {
	ExecuteStatement *ExecuteStatementRequest `protobuf:"bytes,3,opt,name=execute_statement,json=executeStatement,proto3,oneof" json:"execute_statement,omitempty"`
}

func (*ConnectorRequest_Ping) isConnectorRequest_State()             {}
func (*ConnectorRequest_Fetch) isConnectorRequest_State()            {}
func (*ConnectorRequest_ExecuteStatement) isConnectorRequest_State() {}

func (m *ConnectorRequest) GetState() isConnectorRequest_State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *ConnectorRequest) GetPing() *PingRequest {
	if x, ok := m.GetState().(*ConnectorRequest_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *ConnectorRequest) GetFetch() *FetchRequest {
	if x, ok := m.GetState().(*ConnectorRequest_Fetch); ok {
		return x.Fetch
	}
	return nil
}

func (m *ConnectorRequest) GetExecuteStatement() *ExecuteStatementRequest {
	if x, ok := m.GetState().(*ConnectorRequest_ExecuteStatement); ok {
		return x.ExecuteStatement
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ConnectorRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ConnectorRequest_Ping)(nil),
		(*ConnectorRequest_Fetch)(nil),
		(*ConnectorRequest_ExecuteStatement)(nil),
	}
}

type Header struct {
	Columns              []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{3}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

type Column struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *types.Type `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{4}
}
func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type Row struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{5}
}
func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{6}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{7}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{8}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (m *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(m, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

func (m *PingResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type FetchRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{9}
}
func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

type FetchResponse struct {
	Tables               []*node.Table `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *FetchResponse) Reset()         { *m = FetchResponse{} }
func (m *FetchResponse) String() string { return proto.CompactTextString(m) }
func (*FetchResponse) ProtoMessage()    {}
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{10}
}
func (m *FetchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchResponse.Unmarshal(m, b)
}
func (m *FetchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchResponse.Marshal(b, m, deterministic)
}
func (m *FetchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchResponse.Merge(m, src)
}
func (m *FetchResponse) XXX_Size() int {
	return xxx_messageInfo_FetchResponse.Size(m)
}
func (m *FetchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FetchResponse proto.InternalMessageInfo

func (m *FetchResponse) GetTables() []*node.Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

type ExecuteStatementRequest struct {
	Plan                 *plan.Literal `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ExecuteStatementRequest) Reset()         { *m = ExecuteStatementRequest{} }
func (m *ExecuteStatementRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementRequest) ProtoMessage()    {}
func (*ExecuteStatementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{11}
}
func (m *ExecuteStatementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementRequest.Unmarshal(m, b)
}
func (m *ExecuteStatementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementRequest.Merge(m, src)
}
func (m *ExecuteStatementRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementRequest.Size(m)
}
func (m *ExecuteStatementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementRequest proto.InternalMessageInfo

func (m *ExecuteStatementRequest) GetPlan() *plan.Literal {
	if m != nil {
		return m.Plan
	}
	return nil
}

type ExecuteStatementResponse struct {
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteStatementResponse_Header
	//	*ExecuteStatementResponse_Data
	//	*ExecuteStatementResponse_Error
	//	*ExecuteStatementResponse_EOE
	Result               isExecuteStatementResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ExecuteStatementResponse) Reset()         { *m = ExecuteStatementResponse{} }
func (m *ExecuteStatementResponse) String() string { return proto.CompactTextString(m) }
func (*ExecuteStatementResponse) ProtoMessage()    {}
func (*ExecuteStatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f95a54b36234b3cb, []int{12}
}
func (m *ExecuteStatementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteStatementResponse.Unmarshal(m, b)
}
func (m *ExecuteStatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteStatementResponse.Marshal(b, m, deterministic)
}
func (m *ExecuteStatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteStatementResponse.Merge(m, src)
}
func (m *ExecuteStatementResponse) XXX_Size() int {
	return xxx_messageInfo_ExecuteStatementResponse.Size(m)
}
func (m *ExecuteStatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteStatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteStatementResponse proto.InternalMessageInfo

type isExecuteStatementResponse_Result interface {
	isExecuteStatementResponse_Result()
}

type ExecuteStatementResponse_Header struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof" json:"header,omitempty"`
}
type ExecuteStatementResponse_Data struct {
	Data *Row `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}
type ExecuteStatementResponse_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"`
}
type ExecuteStatementResponse_EOE struct {
	EOE *Empty `protobuf:"bytes,4,opt,name=EOE,proto3,oneof" json:"EOE,omitempty"`
}

func (*ExecuteStatementResponse_Header) isExecuteStatementResponse_Result() {}
func (*ExecuteStatementResponse_Data) isExecuteStatementResponse_Result()   {}
func (*ExecuteStatementResponse_Error) isExecuteStatementResponse_Result()  {}
func (*ExecuteStatementResponse_EOE) isExecuteStatementResponse_Result()    {}

func (m *ExecuteStatementResponse) GetResult() isExecuteStatementResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ExecuteStatementResponse) GetHeader() *Header {
	if x, ok := m.GetResult().(*ExecuteStatementResponse_Header); ok {
		return x.Header
	}
	return nil
}

func (m *ExecuteStatementResponse) GetData() *Row {
	if x, ok := m.GetResult().(*ExecuteStatementResponse_Data); ok {
		return x.Data
	}
	return nil
}

func (m *ExecuteStatementResponse) GetError() *Error {
	if x, ok := m.GetResult().(*ExecuteStatementResponse_Error); ok {
		return x.Error
	}
	return nil
}

func (m *ExecuteStatementResponse) GetEOE() *Empty {
	if x, ok := m.GetResult().(*ExecuteStatementResponse_EOE); ok {
		return x.EOE
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExecuteStatementResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExecuteStatementResponse_Header)(nil),
		(*ExecuteStatementResponse_Data)(nil),
		(*ExecuteStatementResponse_Error)(nil),
		(*ExecuteStatementResponse_EOE)(nil),
	}
}

func init() {
	proto.RegisterType((*Empty)(nil), "cloudproud.lunodb.kit.v1.Empty")
	proto.RegisterType((*ConnectorResponse)(nil), "cloudproud.lunodb.kit.v1.ConnectorResponse")
	proto.RegisterType((*ConnectorRequest)(nil), "cloudproud.lunodb.kit.v1.ConnectorRequest")
	proto.RegisterType((*Header)(nil), "cloudproud.lunodb.kit.v1.Header")
	proto.RegisterType((*Column)(nil), "cloudproud.lunodb.kit.v1.Column")
	proto.RegisterType((*Row)(nil), "cloudproud.lunodb.kit.v1.Row")
	proto.RegisterType((*Error)(nil), "cloudproud.lunodb.kit.v1.Error")
	proto.RegisterType((*PingRequest)(nil), "cloudproud.lunodb.kit.v1.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "cloudproud.lunodb.kit.v1.PingResponse")
	proto.RegisterType((*FetchRequest)(nil), "cloudproud.lunodb.kit.v1.FetchRequest")
	proto.RegisterType((*FetchResponse)(nil), "cloudproud.lunodb.kit.v1.FetchResponse")
	proto.RegisterType((*ExecuteStatementRequest)(nil), "cloudproud.lunodb.kit.v1.ExecuteStatementRequest")
	proto.RegisterType((*ExecuteStatementResponse)(nil), "cloudproud.lunodb.kit.v1.ExecuteStatementResponse")
}

func init() { proto.RegisterFile("proto/kit/kit.proto", fileDescriptor_f95a54b36234b3cb) }

var fileDescriptor_f95a54b36234b3cb = []byte{
	// 705 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdf, 0x4e, 0xd4, 0x4e,
	0x14, 0xc7, 0xb7, 0xfb, 0x17, 0x0e, 0xf0, 0x0b, 0xcc, 0x2f, 0xd1, 0x0a, 0x12, 0xb1, 0x41, 0x44,
	0x4d, 0xba, 0x74, 0x89, 0xd1, 0x54, 0xa2, 0xc9, 0x2e, 0xab, 0x9b, 0x2c, 0xc4, 0x4d, 0x31, 0x7b,
	0x61, 0x36, 0xc1, 0x6e, 0x77, 0x5c, 0xaa, 0x6d, 0xa7, 0xb6, 0xd3, 0x45, 0xae, 0x7d, 0x13, 0x2f,
	0x7d, 0x14, 0x1f, 0xc0, 0x07, 0xf0, 0xd2, 0x47, 0xf0, 0xc2, 0x98, 0x99, 0x69, 0xd9, 0x42, 0x32,
	0x0b, 0x5e, 0xd0, 0x30, 0x7b, 0xbe, 0x9f, 0x33, 0xf3, 0x9d, 0x73, 0xe6, 0xc0, 0xff, 0x61, 0x44,
	0x28, 0xa9, 0x7f, 0x74, 0x29, 0xfb, 0xd3, 0xf9, 0x0a, 0xa9, 0x8e, 0x47, 0x92, 0x51, 0x18, 0x91,
	0x64, 0xa4, 0x7b, 0x49, 0x40, 0x46, 0x43, 0x9d, 0x05, 0x27, 0xc6, 0xea, 0xad, 0xa9, 0x3c, 0x20,
	0x23, 0xcc, 0x3f, 0x02, 0xca, 0x87, 0x42, 0xcf, 0x0e, 0xf8, 0x27, 0x0d, 0xad, 0x4d, 0x43, 0xf4,
	0x2c, 0xc4, 0xb1, 0xf8, 0x8a, 0xa0, 0x56, 0x83, 0x4a, 0xdb, 0x0f, 0xe9, 0x99, 0xf6, 0x47, 0x81,
	0x95, 0x16, 0x09, 0x02, 0xec, 0x50, 0x12, 0x59, 0x38, 0x0e, 0x49, 0x10, 0x63, 0xb4, 0x07, 0xe5,
	0xd0, 0x0d, 0xc6, 0xaa, 0xb2, 0xa1, 0x6c, 0x2f, 0x34, 0xb6, 0x74, 0xd9, 0xd1, 0xf4, 0x9e, 0x1b,
	0x8c, 0x33, 0xaa, 0x53, 0xb0, 0x38, 0x85, 0x5e, 0x40, 0xe5, 0x3d, 0xa6, 0xce, 0x89, 0x5a, 0xe4,
	0xf8, 0x7d, 0x39, 0xfe, 0x92, 0xc9, 0x72, 0xbc, 0xe0, 0x90, 0x0d, 0x2b, 0xf8, 0x33, 0x76, 0x12,
	0x8a, 0x8f, 0x63, 0x6a, 0x53, 0xec, 0xe3, 0x80, 0xaa, 0x25, 0x9e, 0xac, 0x21, 0x4f, 0xd6, 0x16,
	0xc8, 0x51, 0x46, 0xe4, 0xf2, 0x2e, 0xe3, 0x4b, 0xb1, 0x66, 0x0d, 0x2a, 0x3c, 0xb5, 0xf6, 0x5b,
	0x81, 0xe5, 0xdc, 0x05, 0x7c, 0x4a, 0x70, 0x4c, 0xd1, 0xb3, 0x0b, 0xfe, 0xef, 0x5d, 0xe5, 0x9f,
	0x43, 0xe7, 0xf6, 0x9f, 0x5f, 0xb4, 0xbf, 0x75, 0xa5, 0xfd, 0x0c, 0x4f, 0xdd, 0xbf, 0x93, 0xbb,
	0x37, 0xfe, 0xc5, 0x7d, 0x96, 0x76, 0x86, 0xf9, 0x7d, 0xa8, 0x76, 0xb0, 0x3d, 0xc2, 0x11, 0x32,
	0xa1, 0xe6, 0x10, 0x2f, 0xf1, 0x83, 0x58, 0x55, 0x36, 0x4a, 0xdb, 0x0b, 0x8d, 0x0d, 0xf9, 0x56,
	0x2d, 0x2e, 0xb4, 0x32, 0x40, 0xeb, 0x43, 0x55, 0xfc, 0x84, 0x10, 0x94, 0x03, 0xdb, 0xc7, 0xfc,
	0xde, 0xe6, 0x2d, 0xfe, 0x3f, 0x7a, 0x0a, 0x65, 0xd6, 0x79, 0xe9, 0x6d, 0x6c, 0x4a, 0xd2, 0x8a,
	0xe6, 0x9c, 0x18, 0xfa, 0x9b, 0xb3, 0x10, 0x5b, 0x9c, 0xd0, 0xd6, 0xa1, 0x64, 0x91, 0x53, 0x74,
	0x03, 0xaa, 0x13, 0xdb, 0x4b, 0xb0, 0x38, 0xd9, 0xa2, 0x95, 0xae, 0xb4, 0xbb, 0x50, 0x69, 0x47,
	0x11, 0x89, 0x90, 0x0a, 0x35, 0x1f, 0xc7, 0xb1, 0x3d, 0xce, 0x36, 0xce, 0x96, 0xda, 0x12, 0x2c,
	0xe4, 0x2a, 0xa4, 0xb5, 0x61, 0x31, 0xdf, 0xb0, 0xe8, 0x31, 0x54, 0x30, 0xcb, 0x90, 0xd6, 0xf9,
	0xce, 0x8c, 0xdb, 0x65, 0x32, 0x4b, 0xa8, 0xb5, 0xff, 0x60, 0x31, 0x5f, 0x39, 0xed, 0x10, 0x96,
	0x2e, 0x34, 0x32, 0xda, 0x83, 0x2a, 0xb5, 0x87, 0x1e, 0xce, 0xee, 0x52, 0x66, 0x9a, 0x3f, 0x64,
	0xe6, 0x99, 0x89, 0xad, 0x94, 0xd1, 0x8e, 0xe1, 0xa6, 0xa4, 0x98, 0x68, 0x1f, 0xca, 0xec, 0x85,
	0xa7, 0xe7, 0xdd, 0x91, 0xa4, 0x75, 0xb2, 0x76, 0xd6, 0xf9, 0x38, 0x98, 0x18, 0xfa, 0x81, 0x4b,
	0x71, 0x64, 0x7b, 0x16, 0xa7, 0xb5, 0x2f, 0x45, 0x50, 0x65, 0x8f, 0x05, 0x99, 0x50, 0x3d, 0xe1,
	0x2d, 0x91, 0x6e, 0x32, 0xa3, 0x0f, 0x44, 0xeb, 0x74, 0x0a, 0x56, 0x4a, 0xa0, 0x5d, 0x28, 0x8f,
	0x6c, 0x6a, 0xa7, 0xa5, 0x5e, 0x97, 0x93, 0x16, 0x39, 0x65, 0xcf, 0x85, 0x89, 0xd1, 0x93, 0xac,
	0x08, 0xa5, 0x6b, 0x15, 0x81, 0xbd, 0x13, 0xae, 0x47, 0xbb, 0x50, 0x6a, 0xbf, 0x6e, 0xab, 0xe5,
	0x2b, 0x31, 0x36, 0xe8, 0x3a, 0x05, 0x8b, 0xa9, 0x9b, 0x73, 0x50, 0x8d, 0x70, 0x9c, 0x78, 0xb4,
	0x91, 0x40, 0xed, 0x08, 0x47, 0x13, 0xd7, 0xc1, 0xe8, 0x03, 0xcc, 0x9f, 0x8f, 0x00, 0xf4, 0x68,
	0x56, 0xe3, 0x5f, 0x1a, 0x94, 0xab, 0x0f, 0xaf, 0x25, 0x16, 0x6d, 0x52, 0xd8, 0x56, 0x76, 0x94,
	0xe6, 0x0f, 0x05, 0x6e, 0x3b, 0xc4, 0x97, 0x72, 0xcd, 0xb9, 0xae, 0x4b, 0x7b, 0x6c, 0x48, 0xf7,
	0x94, 0xb7, 0x0f, 0xc6, 0x2e, 0x3d, 0x49, 0x86, 0xba, 0x43, 0xfc, 0xfa, 0x14, 0xa8, 0xa7, 0x40,
	0x38, 0xac, 0x9f, 0xcf, 0xf8, 0xaf, 0xc5, 0x52, 0xeb, 0xa0, 0xfb, 0xad, 0xa8, 0xb6, 0xa6, 0x79,
	0x0f, 0x84, 0xac, 0xeb, 0x52, 0xbd, 0x6f, 0x7c, 0xcf, 0x87, 0x06, 0x22, 0x34, 0xe8, 0xba, 0x74,
	0xd0, 0x37, 0x7e, 0x16, 0x37, 0x65, 0xa1, 0xc1, 0xab, 0x5e, 0xf3, 0x10, 0x53, 0x9b, 0x55, 0xea,
	0x57, 0x71, 0x6d, 0x2a, 0x33, 0x4d, 0xa1, 0x33, 0xcd, 0xae, 0x4b, 0x4d, 0xb3, 0x6f, 0x0c, 0xab,
	0xfc, 0x2c, 0xbb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x56, 0x2b, 0x9f, 0xdd, 0x06, 0x00,
	0x00,
}
