// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/kit/plan/plan.proto

package plan

import (
	fmt "fmt"
	node "github.com/cloudproud/lunodb.api/proto/kit/node"
	types "github.com/cloudproud/lunodb.pb/proto/kit/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Literal struct {
	Columns              []*Expression     `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	From                 *From             `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Filter               *FilterExpression `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Aggregation          *Aggregation      `protobuf:"bytes,4,opt,name=aggregation,proto3" json:"aggregation,omitempty"`
	OrderBy              *OrderBy          `protobuf:"bytes,5,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Literal) Reset()         { *m = Literal{} }
func (m *Literal) String() string { return proto.CompactTextString(m) }
func (*Literal) ProtoMessage()    {}
func (*Literal) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{0}
}
func (m *Literal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Literal.Unmarshal(m, b)
}
func (m *Literal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Literal.Marshal(b, m, deterministic)
}
func (m *Literal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Literal.Merge(m, src)
}
func (m *Literal) XXX_Size() int {
	return xxx_messageInfo_Literal.Size(m)
}
func (m *Literal) XXX_DiscardUnknown() {
	xxx_messageInfo_Literal.DiscardUnknown(m)
}

var xxx_messageInfo_Literal proto.InternalMessageInfo

func (m *Literal) GetColumns() []*Expression {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Literal) GetFrom() *From {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Literal) GetFilter() *FilterExpression {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *Literal) GetAggregation() *Aggregation {
	if m != nil {
		return m.Aggregation
	}
	return nil
}

func (m *Literal) GetOrderBy() *OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

type From struct {
	Table                string   `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Schema               string   `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *From) Reset()         { *m = From{} }
func (m *From) String() string { return proto.CompactTextString(m) }
func (*From) ProtoMessage()    {}
func (*From) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{1}
}
func (m *From) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_From.Unmarshal(m, b)
}
func (m *From) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_From.Marshal(b, m, deterministic)
}
func (m *From) XXX_Merge(src proto.Message) {
	xxx_messageInfo_From.Merge(m, src)
}
func (m *From) XXX_Size() int {
	return xxx_messageInfo_From.Size(m)
}
func (m *From) XXX_DiscardUnknown() {
	xxx_messageInfo_From.DiscardUnknown(m)
}

var xxx_messageInfo_From proto.InternalMessageInfo

func (m *From) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *From) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

type Expression struct {
	// Types that are valid to be assigned to Statement:
	//
	//	*Expression_Column
	//	*Expression_Function
	//	*Expression_BinaryExpression
	//	*Expression_Constant
	//	*Expression_Tuple
	//	*Expression_Variable
	//	*Expression_Parameter
	//	*Expression_CastExpression
	Statement            isExpression_Statement `protobuf_oneof:"statement"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{2}
}
func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

type isExpression_Statement interface {
	isExpression_Statement()
}

type Expression_Column struct {
	Column *Column `protobuf:"bytes,1,opt,name=column,proto3,oneof" json:"column,omitempty"`
}
type Expression_Function struct {
	Function *Function `protobuf:"bytes,2,opt,name=function,proto3,oneof" json:"function,omitempty"`
}
type Expression_BinaryExpression struct {
	BinaryExpression *BinaryExpression `protobuf:"bytes,3,opt,name=binary_expression,json=binaryExpression,proto3,oneof" json:"binary_expression,omitempty"`
}
type Expression_Constant struct {
	Constant *Constant `protobuf:"bytes,4,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
}
type Expression_Tuple struct {
	Tuple *Tuple `protobuf:"bytes,5,opt,name=tuple,proto3,oneof" json:"tuple,omitempty"`
}
type Expression_Variable struct {
	Variable *VariableExpression `protobuf:"bytes,6,opt,name=variable,proto3,oneof" json:"variable,omitempty"`
}
type Expression_Parameter struct {
	Parameter *Parameter `protobuf:"bytes,7,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`
}
type Expression_CastExpression struct {
	CastExpression *CastExpression `protobuf:"bytes,8,opt,name=cast_expression,json=castExpression,proto3,oneof" json:"cast_expression,omitempty"`
}

func (*Expression_Column) isExpression_Statement()           {}
func (*Expression_Function) isExpression_Statement()         {}
func (*Expression_BinaryExpression) isExpression_Statement() {}
func (*Expression_Constant) isExpression_Statement()         {}
func (*Expression_Tuple) isExpression_Statement()            {}
func (*Expression_Variable) isExpression_Statement()         {}
func (*Expression_Parameter) isExpression_Statement()        {}
func (*Expression_CastExpression) isExpression_Statement()   {}

func (m *Expression) GetStatement() isExpression_Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *Expression) GetColumn() *Column {
	if x, ok := m.GetStatement().(*Expression_Column); ok {
		return x.Column
	}
	return nil
}

func (m *Expression) GetFunction() *Function {
	if x, ok := m.GetStatement().(*Expression_Function); ok {
		return x.Function
	}
	return nil
}

func (m *Expression) GetBinaryExpression() *BinaryExpression {
	if x, ok := m.GetStatement().(*Expression_BinaryExpression); ok {
		return x.BinaryExpression
	}
	return nil
}

func (m *Expression) GetConstant() *Constant {
	if x, ok := m.GetStatement().(*Expression_Constant); ok {
		return x.Constant
	}
	return nil
}

func (m *Expression) GetTuple() *Tuple {
	if x, ok := m.GetStatement().(*Expression_Tuple); ok {
		return x.Tuple
	}
	return nil
}

func (m *Expression) GetVariable() *VariableExpression {
	if x, ok := m.GetStatement().(*Expression_Variable); ok {
		return x.Variable
	}
	return nil
}

func (m *Expression) GetParameter() *Parameter {
	if x, ok := m.GetStatement().(*Expression_Parameter); ok {
		return x.Parameter
	}
	return nil
}

func (m *Expression) GetCastExpression() *CastExpression {
	if x, ok := m.GetStatement().(*Expression_CastExpression); ok {
		return x.CastExpression
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Expression) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Expression_Column)(nil),
		(*Expression_Function)(nil),
		(*Expression_BinaryExpression)(nil),
		(*Expression_Constant)(nil),
		(*Expression_Tuple)(nil),
		(*Expression_Variable)(nil),
		(*Expression_Parameter)(nil),
		(*Expression_CastExpression)(nil),
	}
}

type Column struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Schema               string   `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	Catalog              string   `protobuf:"bytes,4,opt,name=catalog,proto3" json:"catalog,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{3}
}
func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *Column) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Column) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

type FilterExpression struct {
	// Types that are valid to be assigned to Condition:
	//
	//	*FilterExpression_Expression
	//	*FilterExpression_AndExpression
	//	*FilterExpression_OrExpression
	//	*FilterExpression_ComparisonExpression
	Condition            isFilterExpression_Condition `protobuf_oneof:"condition"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *FilterExpression) Reset()         { *m = FilterExpression{} }
func (m *FilterExpression) String() string { return proto.CompactTextString(m) }
func (*FilterExpression) ProtoMessage()    {}
func (*FilterExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{4}
}
func (m *FilterExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterExpression.Unmarshal(m, b)
}
func (m *FilterExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterExpression.Marshal(b, m, deterministic)
}
func (m *FilterExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterExpression.Merge(m, src)
}
func (m *FilterExpression) XXX_Size() int {
	return xxx_messageInfo_FilterExpression.Size(m)
}
func (m *FilterExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterExpression.DiscardUnknown(m)
}

var xxx_messageInfo_FilterExpression proto.InternalMessageInfo

type isFilterExpression_Condition interface {
	isFilterExpression_Condition()
}

type FilterExpression_Expression struct {
	Expression *Expression `protobuf:"bytes,1,opt,name=expression,proto3,oneof" json:"expression,omitempty"`
}
type FilterExpression_AndExpression struct {
	AndExpression *AndExpression `protobuf:"bytes,2,opt,name=and_expression,json=andExpression,proto3,oneof" json:"and_expression,omitempty"`
}
type FilterExpression_OrExpression struct {
	OrExpression *OrExpression `protobuf:"bytes,3,opt,name=or_expression,json=orExpression,proto3,oneof" json:"or_expression,omitempty"`
}
type FilterExpression_ComparisonExpression struct {
	ComparisonExpression *ComparisonExpression `protobuf:"bytes,4,opt,name=comparison_expression,json=comparisonExpression,proto3,oneof" json:"comparison_expression,omitempty"`
}

func (*FilterExpression_Expression) isFilterExpression_Condition()           {}
func (*FilterExpression_AndExpression) isFilterExpression_Condition()        {}
func (*FilterExpression_OrExpression) isFilterExpression_Condition()         {}
func (*FilterExpression_ComparisonExpression) isFilterExpression_Condition() {}

func (m *FilterExpression) GetCondition() isFilterExpression_Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *FilterExpression) GetExpression() *Expression {
	if x, ok := m.GetCondition().(*FilterExpression_Expression); ok {
		return x.Expression
	}
	return nil
}

func (m *FilterExpression) GetAndExpression() *AndExpression {
	if x, ok := m.GetCondition().(*FilterExpression_AndExpression); ok {
		return x.AndExpression
	}
	return nil
}

func (m *FilterExpression) GetOrExpression() *OrExpression {
	if x, ok := m.GetCondition().(*FilterExpression_OrExpression); ok {
		return x.OrExpression
	}
	return nil
}

func (m *FilterExpression) GetComparisonExpression() *ComparisonExpression {
	if x, ok := m.GetCondition().(*FilterExpression_ComparisonExpression); ok {
		return x.ComparisonExpression
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterExpression) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterExpression_Expression)(nil),
		(*FilterExpression_AndExpression)(nil),
		(*FilterExpression_OrExpression)(nil),
		(*FilterExpression_ComparisonExpression)(nil),
	}
}

type Function struct {
	Expressions          []*Expression `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Distinct             bool          `protobuf:"varint,3,opt,name=distinct,proto3" json:"distinct,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{5}
}
func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (m *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(m, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *Function) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Function) GetDistinct() bool {
	if m != nil {
		return m.Distinct
	}
	return false
}

type Aggregation struct {
	GroupBy              []*Expression `protobuf:"bytes,1,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Having               *Expression   `protobuf:"bytes,2,opt,name=having,proto3" json:"having,omitempty"`
	Expressions          []*Expression `protobuf:"bytes,3,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Aggregation) Reset()         { *m = Aggregation{} }
func (m *Aggregation) String() string { return proto.CompactTextString(m) }
func (*Aggregation) ProtoMessage()    {}
func (*Aggregation) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{6}
}
func (m *Aggregation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Aggregation.Unmarshal(m, b)
}
func (m *Aggregation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Aggregation.Marshal(b, m, deterministic)
}
func (m *Aggregation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Aggregation.Merge(m, src)
}
func (m *Aggregation) XXX_Size() int {
	return xxx_messageInfo_Aggregation.Size(m)
}
func (m *Aggregation) XXX_DiscardUnknown() {
	xxx_messageInfo_Aggregation.DiscardUnknown(m)
}

var xxx_messageInfo_Aggregation proto.InternalMessageInfo

func (m *Aggregation) GetGroupBy() []*Expression {
	if m != nil {
		return m.GroupBy
	}
	return nil
}

func (m *Aggregation) GetHaving() *Expression {
	if m != nil {
		return m.Having
	}
	return nil
}

func (m *Aggregation) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type AndExpression struct {
	Left                 *FilterExpression `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                *FilterExpression `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AndExpression) Reset()         { *m = AndExpression{} }
func (m *AndExpression) String() string { return proto.CompactTextString(m) }
func (*AndExpression) ProtoMessage()    {}
func (*AndExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{7}
}
func (m *AndExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndExpression.Unmarshal(m, b)
}
func (m *AndExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndExpression.Marshal(b, m, deterministic)
}
func (m *AndExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndExpression.Merge(m, src)
}
func (m *AndExpression) XXX_Size() int {
	return xxx_messageInfo_AndExpression.Size(m)
}
func (m *AndExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_AndExpression.DiscardUnknown(m)
}

var xxx_messageInfo_AndExpression proto.InternalMessageInfo

func (m *AndExpression) GetLeft() *FilterExpression {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *AndExpression) GetRight() *FilterExpression {
	if m != nil {
		return m.Right
	}
	return nil
}

type OrExpression struct {
	Left                 *FilterExpression `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                *FilterExpression `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrExpression) Reset()         { *m = OrExpression{} }
func (m *OrExpression) String() string { return proto.CompactTextString(m) }
func (*OrExpression) ProtoMessage()    {}
func (*OrExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{8}
}
func (m *OrExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrExpression.Unmarshal(m, b)
}
func (m *OrExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrExpression.Marshal(b, m, deterministic)
}
func (m *OrExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrExpression.Merge(m, src)
}
func (m *OrExpression) XXX_Size() int {
	return xxx_messageInfo_OrExpression.Size(m)
}
func (m *OrExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_OrExpression.DiscardUnknown(m)
}

var xxx_messageInfo_OrExpression proto.InternalMessageInfo

func (m *OrExpression) GetLeft() *FilterExpression {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *OrExpression) GetRight() *FilterExpression {
	if m != nil {
		return m.Right
	}
	return nil
}

type ComparisonExpression struct {
	Operator             node.OperatorStatement `protobuf:"varint,1,opt,name=operator,proto3,enum=cloudproud.lunodb.kit.node.v1.OperatorStatement" json:"operator,omitempty"`
	Left                 *FilterExpression      `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                *FilterExpression      `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	SubOperator          node.OperatorStatement `protobuf:"varint,4,opt,name=sub_operator,json=subOperator,proto3,enum=cloudproud.lunodb.kit.node.v1.OperatorStatement" json:"sub_operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ComparisonExpression) Reset()         { *m = ComparisonExpression{} }
func (m *ComparisonExpression) String() string { return proto.CompactTextString(m) }
func (*ComparisonExpression) ProtoMessage()    {}
func (*ComparisonExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{9}
}
func (m *ComparisonExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComparisonExpression.Unmarshal(m, b)
}
func (m *ComparisonExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComparisonExpression.Marshal(b, m, deterministic)
}
func (m *ComparisonExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComparisonExpression.Merge(m, src)
}
func (m *ComparisonExpression) XXX_Size() int {
	return xxx_messageInfo_ComparisonExpression.Size(m)
}
func (m *ComparisonExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_ComparisonExpression.DiscardUnknown(m)
}

var xxx_messageInfo_ComparisonExpression proto.InternalMessageInfo

func (m *ComparisonExpression) GetOperator() node.OperatorStatement {
	if m != nil {
		return m.Operator
	}
	return node.OperatorUnknown
}

func (m *ComparisonExpression) GetLeft() *FilterExpression {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *ComparisonExpression) GetRight() *FilterExpression {
	if m != nil {
		return m.Right
	}
	return nil
}

func (m *ComparisonExpression) GetSubOperator() node.OperatorStatement {
	if m != nil {
		return m.SubOperator
	}
	return node.OperatorUnknown
}

type BinaryExpression struct {
	Operator             node.BinaryStatement `protobuf:"varint,1,opt,name=operator,proto3,enum=cloudproud.lunodb.kit.node.v1.BinaryStatement" json:"operator,omitempty"`
	Left                 *Expression          `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                *Expression          `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BinaryExpression) Reset()         { *m = BinaryExpression{} }
func (m *BinaryExpression) String() string { return proto.CompactTextString(m) }
func (*BinaryExpression) ProtoMessage()    {}
func (*BinaryExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{10}
}
func (m *BinaryExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryExpression.Unmarshal(m, b)
}
func (m *BinaryExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryExpression.Marshal(b, m, deterministic)
}
func (m *BinaryExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryExpression.Merge(m, src)
}
func (m *BinaryExpression) XXX_Size() int {
	return xxx_messageInfo_BinaryExpression.Size(m)
}
func (m *BinaryExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryExpression.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryExpression proto.InternalMessageInfo

func (m *BinaryExpression) GetOperator() node.BinaryStatement {
	if m != nil {
		return m.Operator
	}
	return node.BinaryStatementUnknown
}

func (m *BinaryExpression) GetLeft() *Expression {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *BinaryExpression) GetRight() *Expression {
	if m != nil {
		return m.Right
	}
	return nil
}

type CastExpression struct {
	Type                 *types.Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Expression           *Expression `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CastExpression) Reset()         { *m = CastExpression{} }
func (m *CastExpression) String() string { return proto.CompactTextString(m) }
func (*CastExpression) ProtoMessage()    {}
func (*CastExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{11}
}
func (m *CastExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CastExpression.Unmarshal(m, b)
}
func (m *CastExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CastExpression.Marshal(b, m, deterministic)
}
func (m *CastExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CastExpression.Merge(m, src)
}
func (m *CastExpression) XXX_Size() int {
	return xxx_messageInfo_CastExpression.Size(m)
}
func (m *CastExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_CastExpression.DiscardUnknown(m)
}

var xxx_messageInfo_CastExpression proto.InternalMessageInfo

func (m *CastExpression) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *CastExpression) GetExpression() *Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

type Constant struct {
	Type                 *types.Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Constant) Reset()         { *m = Constant{} }
func (m *Constant) String() string { return proto.CompactTextString(m) }
func (*Constant) ProtoMessage()    {}
func (*Constant) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{12}
}
func (m *Constant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Constant.Unmarshal(m, b)
}
func (m *Constant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Constant.Marshal(b, m, deterministic)
}
func (m *Constant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Constant.Merge(m, src)
}
func (m *Constant) XXX_Size() int {
	return xxx_messageInfo_Constant.Size(m)
}
func (m *Constant) XXX_DiscardUnknown() {
	xxx_messageInfo_Constant.DiscardUnknown(m)
}

var xxx_messageInfo_Constant proto.InternalMessageInfo

func (m *Constant) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Constant) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type OrderBy struct {
	Expressions          []*OrderExpression `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *OrderBy) Reset()         { *m = OrderBy{} }
func (m *OrderBy) String() string { return proto.CompactTextString(m) }
func (*OrderBy) ProtoMessage()    {}
func (*OrderBy) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{13}
}
func (m *OrderBy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderBy.Unmarshal(m, b)
}
func (m *OrderBy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderBy.Marshal(b, m, deterministic)
}
func (m *OrderBy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBy.Merge(m, src)
}
func (m *OrderBy) XXX_Size() int {
	return xxx_messageInfo_OrderBy.Size(m)
}
func (m *OrderBy) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBy.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBy proto.InternalMessageInfo

func (m *OrderBy) GetExpressions() []*OrderExpression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type OrderExpression struct {
	Direction            uint32      `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Expression           *Expression `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OrderExpression) Reset()         { *m = OrderExpression{} }
func (m *OrderExpression) String() string { return proto.CompactTextString(m) }
func (*OrderExpression) ProtoMessage()    {}
func (*OrderExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{14}
}
func (m *OrderExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderExpression.Unmarshal(m, b)
}
func (m *OrderExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderExpression.Marshal(b, m, deterministic)
}
func (m *OrderExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderExpression.Merge(m, src)
}
func (m *OrderExpression) XXX_Size() int {
	return xxx_messageInfo_OrderExpression.Size(m)
}
func (m *OrderExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderExpression.DiscardUnknown(m)
}

var xxx_messageInfo_OrderExpression proto.InternalMessageInfo

func (m *OrderExpression) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *OrderExpression) GetExpression() *Expression {
	if m != nil {
		return m.Expression
	}
	return nil
}

type Tuple struct {
	Expressions          []*Expression `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Tuple) Reset()         { *m = Tuple{} }
func (m *Tuple) String() string { return proto.CompactTextString(m) }
func (*Tuple) ProtoMessage()    {}
func (*Tuple) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{15}
}
func (m *Tuple) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tuple.Unmarshal(m, b)
}
func (m *Tuple) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tuple.Marshal(b, m, deterministic)
}
func (m *Tuple) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tuple.Merge(m, src)
}
func (m *Tuple) XXX_Size() int {
	return xxx_messageInfo_Tuple.Size(m)
}
func (m *Tuple) XXX_DiscardUnknown() {
	xxx_messageInfo_Tuple.DiscardUnknown(m)
}

var xxx_messageInfo_Tuple proto.InternalMessageInfo

func (m *Tuple) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type VariableExpression struct {
	Offset               uint64   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VariableExpression) Reset()         { *m = VariableExpression{} }
func (m *VariableExpression) String() string { return proto.CompactTextString(m) }
func (*VariableExpression) ProtoMessage()    {}
func (*VariableExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{16}
}
func (m *VariableExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableExpression.Unmarshal(m, b)
}
func (m *VariableExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableExpression.Marshal(b, m, deterministic)
}
func (m *VariableExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableExpression.Merge(m, src)
}
func (m *VariableExpression) XXX_Size() int {
	return xxx_messageInfo_VariableExpression.Size(m)
}
func (m *VariableExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableExpression.DiscardUnknown(m)
}

var xxx_messageInfo_VariableExpression proto.InternalMessageInfo

func (m *VariableExpression) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type Parameter struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parameter) Reset()         { *m = Parameter{} }
func (m *Parameter) String() string { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()    {}
func (*Parameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_396af971f72480a3, []int{17}
}
func (m *Parameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parameter.Unmarshal(m, b)
}
func (m *Parameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parameter.Marshal(b, m, deterministic)
}
func (m *Parameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parameter.Merge(m, src)
}
func (m *Parameter) XXX_Size() int {
	return xxx_messageInfo_Parameter.Size(m)
}
func (m *Parameter) XXX_DiscardUnknown() {
	xxx_messageInfo_Parameter.DiscardUnknown(m)
}

var xxx_messageInfo_Parameter proto.InternalMessageInfo

func (m *Parameter) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func init() {
	proto.RegisterType((*Literal)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Literal")
	proto.RegisterType((*From)(nil), "cloudproud.lunodb.kit.connector.plan.v1.From")
	proto.RegisterType((*Expression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Expression")
	proto.RegisterType((*Column)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Column")
	proto.RegisterType((*FilterExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.FilterExpression")
	proto.RegisterType((*Function)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Function")
	proto.RegisterType((*Aggregation)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Aggregation")
	proto.RegisterType((*AndExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.AndExpression")
	proto.RegisterType((*OrExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.OrExpression")
	proto.RegisterType((*ComparisonExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.ComparisonExpression")
	proto.RegisterType((*BinaryExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.BinaryExpression")
	proto.RegisterType((*CastExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.CastExpression")
	proto.RegisterType((*Constant)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Constant")
	proto.RegisterType((*OrderBy)(nil), "cloudproud.lunodb.kit.connector.plan.v1.OrderBy")
	proto.RegisterType((*OrderExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.OrderExpression")
	proto.RegisterType((*Tuple)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Tuple")
	proto.RegisterType((*VariableExpression)(nil), "cloudproud.lunodb.kit.connector.plan.v1.VariableExpression")
	proto.RegisterType((*Parameter)(nil), "cloudproud.lunodb.kit.connector.plan.v1.Parameter")
}

func init() { proto.RegisterFile("proto/kit/plan/plan.proto", fileDescriptor_396af971f72480a3) }

var fileDescriptor_396af971f72480a3 = []byte{
	// 1133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x97, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc7, 0x63, 0xe7, 0xfb, 0xa4, 0xed, 0x2e, 0xa3, 0x82, 0x42, 0xe1, 0xa2, 0x58, 0x48, 0x5b,
	0x89, 0xc5, 0x21, 0xed, 0x02, 0x4b, 0x10, 0x17, 0x9b, 0x8a, 0xdd, 0x2c, 0x69, 0x69, 0x70, 0xd9,
	0x4a, 0x54, 0x11, 0xd5, 0xd8, 0x9e, 0xa4, 0xd6, 0x3a, 0x33, 0x96, 0x3d, 0xae, 0x36, 0x97, 0x48,
	0xbc, 0x00, 0xe2, 0x01, 0x90, 0xb8, 0x64, 0x25, 0x78, 0x0f, 0x78, 0x02, 0x6e, 0xb9, 0xe4, 0x92,
	0x27, 0x40, 0x9e, 0x71, 0xfc, 0xd1, 0x0f, 0xe1, 0x36, 0x5d, 0x89, 0x1b, 0xcb, 0x33, 0x9e, 0xf3,
	0x9b, 0x33, 0xff, 0x99, 0x73, 0xe6, 0x18, 0xde, 0xf4, 0x7c, 0xc6, 0x59, 0xe7, 0xb9, 0xc3, 0x3b,
	0x9e, 0x8b, 0xa9, 0x78, 0xe8, 0xa2, 0x0f, 0xdd, 0xb3, 0x5c, 0x16, 0xda, 0x9e, 0xcf, 0x42, 0x5b,
	0x77, 0x43, 0xca, 0x6c, 0x53, 0x7f, 0xee, 0x70, 0xdd, 0x62, 0x94, 0x12, 0x8b, 0x33, 0x5f, 0x17,
	0x63, 0xcf, 0xba, 0x1b, 0xeb, 0x53, 0x36, 0x65, 0x92, 0x13, 0xbd, 0x49, 0xf3, 0x8d, 0x0c, 0x99,
	0x32, 0x9b, 0x88, 0x47, 0xfc, 0xe9, 0xad, 0xf4, 0x13, 0x9f, 0x7b, 0x24, 0x90, 0x4f, 0xf9, 0x51,
	0xfb, 0xb1, 0x0c, 0xf5, 0x3d, 0x87, 0x13, 0x1f, 0xbb, 0x68, 0x1f, 0xea, 0x16, 0x73, 0xc3, 0x19,
	0x0d, 0xda, 0xca, 0x66, 0x79, 0xab, 0xb5, 0xbd, 0xa3, 0x17, 0x74, 0x4a, 0xff, 0xfc, 0x85, 0xe7,
	0x93, 0x20, 0x70, 0x18, 0x35, 0x16, 0x0c, 0xf4, 0x08, 0x2a, 0x13, 0x9f, 0xcd, 0xda, 0xea, 0xa6,
	0xb2, 0xd5, 0xda, 0x7e, 0xbf, 0x30, 0xeb, 0xb1, 0xcf, 0x66, 0x86, 0x30, 0x45, 0x5f, 0x41, 0x6d,
	0xe2, 0xb8, 0x9c, 0xf8, 0xed, 0xb2, 0x80, 0x7c, 0x52, 0x1c, 0x22, 0xcc, 0x32, 0x6e, 0xc5, 0x20,
	0x74, 0x04, 0x2d, 0x3c, 0x9d, 0xfa, 0x64, 0x8a, 0xb9, 0xc3, 0x68, 0xbb, 0x22, 0xb8, 0x0f, 0x0a,
	0x73, 0x1f, 0xa5, 0xb6, 0x46, 0x16, 0x84, 0x86, 0xd0, 0x60, 0xbe, 0x4d, 0xfc, 0x13, 0x73, 0xde,
	0xae, 0x0a, 0xe8, 0x07, 0x85, 0xa1, 0x07, 0x91, 0x61, 0x7f, 0x6e, 0xd4, 0x99, 0x7c, 0xd1, 0x1e,
	0x40, 0x25, 0x52, 0x01, 0xad, 0x43, 0x95, 0x63, 0xd3, 0x25, 0x6d, 0x65, 0x53, 0xd9, 0x6a, 0x1a,
	0xb2, 0x81, 0xde, 0x80, 0x5a, 0x60, 0x9d, 0x92, 0x19, 0x16, 0xd2, 0x36, 0x8d, 0xb8, 0xa5, 0xfd,
	0x51, 0x05, 0x48, 0x57, 0x8c, 0x9e, 0x42, 0x4d, 0x6e, 0x85, 0xb0, 0x6e, 0x6d, 0x77, 0x0a, 0xfb,
	0xb3, 0x2b, 0xcc, 0x06, 0x25, 0x23, 0x06, 0xa0, 0x03, 0x68, 0x4c, 0x42, 0x6a, 0x09, 0xc5, 0xe4,
	0x76, 0x76, 0x8b, 0xef, 0x44, 0x6c, 0x38, 0x28, 0x19, 0x09, 0x04, 0x9d, 0xc2, 0x6b, 0xa6, 0x43,
	0xb1, 0x3f, 0x3f, 0x21, 0x89, 0xc3, 0xd7, 0xde, 0xe3, 0xbe, 0x20, 0xa4, 0x2b, 0x1e, 0x94, 0x8c,
	0xbb, 0xe6, 0xb9, 0xbe, 0xc8, 0x75, 0x8b, 0xd1, 0x80, 0x63, 0xca, 0xe3, 0xcd, 0xee, 0x5e, 0x43,
	0x07, 0x69, 0x18, 0xb9, 0xbe, 0x80, 0xa0, 0xc7, 0x50, 0xe5, 0xa1, 0xe7, 0x92, 0x78, 0x97, 0xf5,
	0xc2, 0xb4, 0xaf, 0x23, 0xab, 0x41, 0xc9, 0x90, 0xe6, 0xe8, 0x1b, 0x68, 0x9c, 0x61, 0xdf, 0x11,
	0xdb, 0x5b, 0x13, 0xa8, 0x4f, 0x0b, 0xa3, 0x8e, 0x62, 0xc3, 0xdc, 0xda, 0x13, 0x1c, 0x32, 0xa0,
	0xe9, 0x61, 0x1f, 0xcf, 0x48, 0x14, 0x39, 0x75, 0xc1, 0xde, 0x2e, 0xcc, 0x1e, 0x2d, 0x2c, 0x07,
	0x25, 0x23, 0xc5, 0x20, 0x13, 0xee, 0x58, 0x38, 0xe0, 0xd9, 0xfd, 0x6a, 0x08, 0xf2, 0xc7, 0xc5,
	0xe5, 0xc4, 0x01, 0xcf, 0x79, 0xbc, 0x66, 0xe5, 0x7a, 0xfa, 0x2d, 0x68, 0x06, 0x1c, 0x73, 0x32,
	0x23, 0x94, 0x6b, 0x36, 0xd4, 0xe4, 0x39, 0x44, 0x08, 0x2a, 0x14, 0xcf, 0x16, 0x41, 0x20, 0xde,
	0xd3, 0xc8, 0x50, 0x2f, 0x8f, 0x8c, 0x72, 0x36, 0x32, 0x50, 0x1b, 0xea, 0x16, 0xe6, 0xd8, 0x65,
	0x53, 0x71, 0x06, 0x9a, 0xc6, 0xa2, 0xa9, 0xbd, 0x2c, 0xc3, 0xdd, 0xf3, 0xb9, 0x02, 0x3d, 0x03,
	0xc8, 0x2c, 0x53, 0x46, 0xcf, 0x4d, 0x72, 0xe1, 0xa0, 0x64, 0x64, 0x40, 0xe8, 0x04, 0xd6, 0x30,
	0xb5, 0xb3, 0x0a, 0xca, 0x58, 0xfa, 0xa8, 0x78, 0xf6, 0xa1, 0x76, 0x8e, 0xbe, 0x8a, 0xb3, 0x1d,
	0x68, 0x0c, 0xab, 0xcc, 0xbf, 0x18, 0x51, 0x1f, 0x5e, 0x23, 0x11, 0xe5, 0xf0, 0x2b, 0x2c, 0xab,
	0x0a, 0x87, 0xd7, 0x2d, 0x36, 0xf3, 0xb0, 0xef, 0x04, 0x8c, 0x66, 0x67, 0x91, 0x61, 0xf5, 0xd9,
	0x35, 0xc2, 0x6a, 0x41, 0xc9, 0xcd, 0xb6, 0x6e, 0x5d, 0xd2, 0x1f, 0x9d, 0x09, 0x8b, 0x51, 0xdb,
	0x89, 0xd2, 0x86, 0xf6, 0x83, 0x02, 0x8d, 0x45, 0x3e, 0x41, 0xcf, 0xa0, 0x95, 0x3a, 0xb1, 0xd4,
	0x95, 0x95, 0xe5, 0x24, 0xa7, 0x4d, 0xcd, 0x9c, 0xb6, 0x0d, 0x68, 0xd8, 0x4e, 0xc0, 0x1d, 0x6a,
	0x71, 0xa1, 0x69, 0xc3, 0x48, 0xda, 0xda, 0x77, 0x2a, 0xb4, 0x32, 0xb7, 0x02, 0xfa, 0x12, 0x1a,
	0x53, 0x9f, 0x85, 0x5e, 0x74, 0x11, 0x2c, 0x73, 0x8d, 0x0a, 0x48, 0x7f, 0x8e, 0x86, 0x50, 0x3b,
	0xc5, 0x67, 0x0e, 0x9d, 0xc6, 0xa7, 0xe5, 0x46, 0xb4, 0x18, 0x71, 0x5e, 0xb3, 0xf2, 0xed, 0x68,
	0xa6, 0xfd, 0xa6, 0xc0, 0x6a, 0xee, 0x6c, 0xa2, 0x7d, 0xa8, 0xb8, 0x64, 0xc2, 0xe3, 0xe0, 0x59,
	0xe2, 0xde, 0x16, 0x18, 0x74, 0x00, 0x55, 0xdf, 0x99, 0x9e, 0xf2, 0x58, 0x83, 0x25, 0x78, 0x92,
	0xa3, 0xfd, 0xaa, 0xc0, 0x4a, 0xf6, 0xb4, 0xff, 0xef, 0x1d, 0xfe, 0x53, 0x85, 0xf5, 0xcb, 0x02,
	0x07, 0xed, 0x41, 0x83, 0x79, 0xc4, 0xc7, 0x9c, 0xf9, 0xc2, 0xf9, 0xb5, 0x2b, 0x0b, 0x0f, 0x51,
	0x13, 0x46, 0x51, 0x1e, 0x0f, 0x3f, 0x5c, 0xe4, 0x5a, 0x23, 0x21, 0x24, 0x32, 0xa8, 0xb7, 0x2c,
	0x43, 0xf9, 0x76, 0x64, 0x40, 0x87, 0xb0, 0x12, 0x84, 0xe6, 0x49, 0xb2, 0xe2, 0xca, 0x0d, 0x57,
	0xdc, 0x0a, 0x42, 0x73, 0xd1, 0xab, 0xfd, 0xa3, 0xc0, 0xdd, 0xf3, 0xc5, 0x04, 0xfa, 0xe2, 0x82,
	0xae, 0xfa, 0x7f, 0xcc, 0x22, 0x11, 0x97, 0xa9, 0xfa, 0x24, 0xa7, 0xea, 0x8d, 0xe2, 0x4d, 0xea,
	0xf9, 0x34, 0xaf, 0xe7, 0x8d, 0x48, 0xf1, 0x81, 0xfa, 0x49, 0x81, 0xb5, 0xfc, 0x8d, 0x8c, 0x1e,
	0x42, 0x25, 0xfa, 0x37, 0x88, 0x63, 0xe0, 0xdd, 0x2b, 0xe0, 0xf2, 0xf7, 0x21, 0x2a, 0x68, 0xe6,
	0x1e, 0x31, 0x84, 0x05, 0x3a, 0xcc, 0xdd, 0x98, 0x4b, 0x2c, 0x33, 0x83, 0xd1, 0x8e, 0xa1, 0xb1,
	0xa8, 0xc0, 0x96, 0x70, 0x6d, 0x1d, 0xaa, 0x67, 0xd8, 0x0d, 0x65, 0x42, 0x5f, 0x31, 0x64, 0x43,
	0x23, 0x50, 0x8f, 0xab, 0x6e, 0x74, 0x7c, 0xd9, 0x3d, 0xf2, 0xf0, 0x7a, 0xc5, 0xfb, 0x55, 0x89,
	0xf1, 0x7b, 0x05, 0xee, 0x9c, 0x1b, 0x80, 0xde, 0x86, 0xa6, 0xed, 0xf8, 0x44, 0x56, 0xd3, 0xd1,
	0x7a, 0x56, 0x8d, 0xb4, 0xe3, 0xd5, 0x28, 0xf9, 0x2d, 0x54, 0x45, 0xf5, 0xf9, 0x8a, 0xee, 0x4c,
	0xed, 0x3e, 0xa0, 0x8b, 0x25, 0x69, 0x54, 0x8d, 0xb1, 0xc9, 0x24, 0x20, 0x32, 0xa9, 0x56, 0x8c,
	0xb8, 0xa5, 0xbd, 0x03, 0xcd, 0xa4, 0xc8, 0x8c, 0xb6, 0xc7, 0xa1, 0x36, 0x79, 0x11, 0x2b, 0x21,
	0x1b, 0xfd, 0x97, 0x2a, 0xbc, 0x67, 0xb1, 0x59, 0x51, 0xc7, 0xfa, 0xcd, 0x91, 0x8b, 0xe9, 0x28,
	0xfa, 0xa3, 0x1d, 0x29, 0xc7, 0xfa, 0xd4, 0xe1, 0xa7, 0xa1, 0xa9, 0x5b, 0x6c, 0xd6, 0x49, 0x01,
	0x9d, 0x18, 0xe0, 0x99, 0x9d, 0xfc, 0x5f, 0xf8, 0xcf, 0x6a, 0x75, 0x77, 0x6f, 0xb8, 0x3b, 0xfa,
	0x45, 0xbd, 0xb7, 0x9b, 0x4e, 0xb7, 0x27, 0x47, 0x0f, 0x1d, 0x1e, 0xfd, 0x06, 0xc4, 0xd3, 0x45,
	0xb3, 0xe8, 0x47, 0xdd, 0xdf, 0xb3, 0x23, 0xc7, 0x72, 0xe4, 0x78, 0xe8, 0xf0, 0x71, 0x32, 0x72,
	0x1c, 0x8d, 0x1c, 0x1f, 0x75, 0xff, 0x52, 0x77, 0x0a, 0x8e, 0x1c, 0x3f, 0x19, 0xf5, 0xf7, 0x09,
	0xc7, 0x36, 0xe6, 0xf8, 0x6f, 0xf5, 0x7e, 0x6a, 0xd5, 0xeb, 0x49, 0xb3, 0x5e, 0x6f, 0xe8, 0xf0,
	0x5e, 0x2f, 0x31, 0xec, 0xf5, 0x22, 0xcb, 0x5e, 0xef, 0xa8, 0x6b, 0xd6, 0xc4, 0x82, 0x76, 0xfe,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x38, 0x41, 0xaa, 0x36, 0x5f, 0x10, 0x00, 0x00,
}
