// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/plan/plan.proto

package plan

import (
	fmt "fmt"
	node "github.com/cloudproud/lunodb.api/proto/node"
	types "github.com/cloudproud/lunodb.api/proto/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	// Types that are valid to be assigned to Plan:
	//
	//	*Node_Scanner
	//	*Node_Column
	//	*Node_Filter
	//	*Node_Function
	//	*Node_Aggregation
	//	*Node_AndExpression
	//	*Node_OrExpression
	//	*Node_ComparisonExpression
	//	*Node_BinaryExpression
	//	*Node_CastExpression
	//	*Node_CaseExpression
	//	*Node_Constant
	//	*Node_Tuple
	//	*Node_Variable
	//	*Node_OrderBy
	//	*Node_Values
	//	*Node_Parameter
	//	*Node_Distinct
	//	*Node_Reference
	//	*Node_Value
	Plan                 isNode_Plan `protobuf_oneof:"plan"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{0}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

type isNode_Plan interface {
	isNode_Plan()
}

type Node_Scanner struct {
	Scanner *ScannerNode `protobuf:"bytes,1,opt,name=scanner,proto3,oneof" json:"scanner,omitempty"`
}
type Node_Column struct {
	Column *ColumnNode `protobuf:"bytes,2,opt,name=column,proto3,oneof" json:"column,omitempty"`
}
type Node_Filter struct {
	Filter *FilterNode `protobuf:"bytes,3,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
}
type Node_Function struct {
	Function *FunctionNode `protobuf:"bytes,4,opt,name=function,proto3,oneof" json:"function,omitempty"`
}
type Node_Aggregation struct {
	Aggregation *AggregationNode `protobuf:"bytes,5,opt,name=aggregation,proto3,oneof" json:"aggregation,omitempty"`
}
type Node_AndExpression struct {
	AndExpression *AndExpressionNode `protobuf:"bytes,7,opt,name=and_expression,json=andExpression,proto3,oneof" json:"and_expression,omitempty"`
}
type Node_OrExpression struct {
	OrExpression *OrExpressionNode `protobuf:"bytes,8,opt,name=or_expression,json=orExpression,proto3,oneof" json:"or_expression,omitempty"`
}
type Node_ComparisonExpression struct {
	ComparisonExpression *ComparisonExpressionNode `protobuf:"bytes,9,opt,name=comparison_expression,json=comparisonExpression,proto3,oneof" json:"comparison_expression,omitempty"`
}
type Node_BinaryExpression struct {
	BinaryExpression *BinaryExpressionNode `protobuf:"bytes,10,opt,name=binary_expression,json=binaryExpression,proto3,oneof" json:"binary_expression,omitempty"`
}
type Node_CastExpression struct {
	CastExpression *CastExpression `protobuf:"bytes,11,opt,name=cast_expression,json=castExpression,proto3,oneof" json:"cast_expression,omitempty"`
}
type Node_CaseExpression struct {
	CaseExpression *CaseExpressionNode `protobuf:"bytes,12,opt,name=case_expression,json=caseExpression,proto3,oneof" json:"case_expression,omitempty"`
}
type Node_Constant struct {
	Constant *ConstantNode `protobuf:"bytes,13,opt,name=constant,proto3,oneof" json:"constant,omitempty"`
}
type Node_Tuple struct {
	Tuple *TupleNode `protobuf:"bytes,18,opt,name=tuple,proto3,oneof" json:"tuple,omitempty"`
}
type Node_Variable struct {
	Variable *VariableExpression `protobuf:"bytes,19,opt,name=variable,proto3,oneof" json:"variable,omitempty"`
}
type Node_OrderBy struct {
	OrderBy *OrderByNode `protobuf:"bytes,20,opt,name=order_by,json=orderBy,proto3,oneof" json:"order_by,omitempty"`
}
type Node_Values struct {
	Values *ValuesClauseNode `protobuf:"bytes,21,opt,name=values,proto3,oneof" json:"values,omitempty"`
}
type Node_Parameter struct {
	Parameter *ParameterNode `protobuf:"bytes,25,opt,name=parameter,proto3,oneof" json:"parameter,omitempty"`
}
type Node_Distinct struct {
	Distinct *DistinctNode `protobuf:"bytes,28,opt,name=distinct,proto3,oneof" json:"distinct,omitempty"`
}
type Node_Reference struct {
	Reference *ReferenceNode `protobuf:"bytes,31,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
}
type Node_Value struct {
	Value *ValueNode `protobuf:"bytes,32,opt,name=value,proto3,oneof" json:"value,omitempty"`
}

func (*Node_Scanner) isNode_Plan()              {}
func (*Node_Column) isNode_Plan()               {}
func (*Node_Filter) isNode_Plan()               {}
func (*Node_Function) isNode_Plan()             {}
func (*Node_Aggregation) isNode_Plan()          {}
func (*Node_AndExpression) isNode_Plan()        {}
func (*Node_OrExpression) isNode_Plan()         {}
func (*Node_ComparisonExpression) isNode_Plan() {}
func (*Node_BinaryExpression) isNode_Plan()     {}
func (*Node_CastExpression) isNode_Plan()       {}
func (*Node_CaseExpression) isNode_Plan()       {}
func (*Node_Constant) isNode_Plan()             {}
func (*Node_Tuple) isNode_Plan()                {}
func (*Node_Variable) isNode_Plan()             {}
func (*Node_OrderBy) isNode_Plan()              {}
func (*Node_Values) isNode_Plan()               {}
func (*Node_Parameter) isNode_Plan()            {}
func (*Node_Distinct) isNode_Plan()             {}
func (*Node_Reference) isNode_Plan()            {}
func (*Node_Value) isNode_Plan()                {}

func (m *Node) GetPlan() isNode_Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *Node) GetScanner() *ScannerNode {
	if x, ok := m.GetPlan().(*Node_Scanner); ok {
		return x.Scanner
	}
	return nil
}

func (m *Node) GetColumn() *ColumnNode {
	if x, ok := m.GetPlan().(*Node_Column); ok {
		return x.Column
	}
	return nil
}

func (m *Node) GetFilter() *FilterNode {
	if x, ok := m.GetPlan().(*Node_Filter); ok {
		return x.Filter
	}
	return nil
}

func (m *Node) GetFunction() *FunctionNode {
	if x, ok := m.GetPlan().(*Node_Function); ok {
		return x.Function
	}
	return nil
}

func (m *Node) GetAggregation() *AggregationNode {
	if x, ok := m.GetPlan().(*Node_Aggregation); ok {
		return x.Aggregation
	}
	return nil
}

func (m *Node) GetAndExpression() *AndExpressionNode {
	if x, ok := m.GetPlan().(*Node_AndExpression); ok {
		return x.AndExpression
	}
	return nil
}

func (m *Node) GetOrExpression() *OrExpressionNode {
	if x, ok := m.GetPlan().(*Node_OrExpression); ok {
		return x.OrExpression
	}
	return nil
}

func (m *Node) GetComparisonExpression() *ComparisonExpressionNode {
	if x, ok := m.GetPlan().(*Node_ComparisonExpression); ok {
		return x.ComparisonExpression
	}
	return nil
}

func (m *Node) GetBinaryExpression() *BinaryExpressionNode {
	if x, ok := m.GetPlan().(*Node_BinaryExpression); ok {
		return x.BinaryExpression
	}
	return nil
}

func (m *Node) GetCastExpression() *CastExpression {
	if x, ok := m.GetPlan().(*Node_CastExpression); ok {
		return x.CastExpression
	}
	return nil
}

func (m *Node) GetCaseExpression() *CaseExpressionNode {
	if x, ok := m.GetPlan().(*Node_CaseExpression); ok {
		return x.CaseExpression
	}
	return nil
}

func (m *Node) GetConstant() *ConstantNode {
	if x, ok := m.GetPlan().(*Node_Constant); ok {
		return x.Constant
	}
	return nil
}

func (m *Node) GetTuple() *TupleNode {
	if x, ok := m.GetPlan().(*Node_Tuple); ok {
		return x.Tuple
	}
	return nil
}

func (m *Node) GetVariable() *VariableExpression {
	if x, ok := m.GetPlan().(*Node_Variable); ok {
		return x.Variable
	}
	return nil
}

func (m *Node) GetOrderBy() *OrderByNode {
	if x, ok := m.GetPlan().(*Node_OrderBy); ok {
		return x.OrderBy
	}
	return nil
}

func (m *Node) GetValues() *ValuesClauseNode {
	if x, ok := m.GetPlan().(*Node_Values); ok {
		return x.Values
	}
	return nil
}

func (m *Node) GetParameter() *ParameterNode {
	if x, ok := m.GetPlan().(*Node_Parameter); ok {
		return x.Parameter
	}
	return nil
}

func (m *Node) GetDistinct() *DistinctNode {
	if x, ok := m.GetPlan().(*Node_Distinct); ok {
		return x.Distinct
	}
	return nil
}

func (m *Node) GetReference() *ReferenceNode {
	if x, ok := m.GetPlan().(*Node_Reference); ok {
		return x.Reference
	}
	return nil
}

func (m *Node) GetValue() *ValueNode {
	if x, ok := m.GetPlan().(*Node_Value); ok {
		return x.Value
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Node) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Node_Scanner)(nil),
		(*Node_Column)(nil),
		(*Node_Filter)(nil),
		(*Node_Function)(nil),
		(*Node_Aggregation)(nil),
		(*Node_AndExpression)(nil),
		(*Node_OrExpression)(nil),
		(*Node_ComparisonExpression)(nil),
		(*Node_BinaryExpression)(nil),
		(*Node_CastExpression)(nil),
		(*Node_CaseExpression)(nil),
		(*Node_Constant)(nil),
		(*Node_Tuple)(nil),
		(*Node_Variable)(nil),
		(*Node_OrderBy)(nil),
		(*Node_Values)(nil),
		(*Node_Parameter)(nil),
		(*Node_Distinct)(nil),
		(*Node_Reference)(nil),
		(*Node_Value)(nil),
	}
}

type ColumnNode struct {
	ID                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Table                string           `protobuf:"bytes,3,opt,name=table,proto3" json:"table,omitempty"`
	Schema               string           `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	Catalog              string           `protobuf:"bytes,5,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Node                 *Node            `protobuf:"bytes,6,opt,name=node,proto3" json:"node,omitempty"`
	Operators            []*node.Operator `protobuf:"bytes,7,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ColumnNode) Reset()         { *m = ColumnNode{} }
func (m *ColumnNode) String() string { return proto.CompactTextString(m) }
func (*ColumnNode) ProtoMessage()    {}
func (*ColumnNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{1}
}
func (m *ColumnNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ColumnNode.Unmarshal(m, b)
}
func (m *ColumnNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ColumnNode.Marshal(b, m, deterministic)
}
func (m *ColumnNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ColumnNode.Merge(m, src)
}
func (m *ColumnNode) XXX_Size() int {
	return xxx_messageInfo_ColumnNode.Size(m)
}
func (m *ColumnNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ColumnNode.DiscardUnknown(m)
}

var xxx_messageInfo_ColumnNode proto.InternalMessageInfo

func (m *ColumnNode) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *ColumnNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ColumnNode) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ColumnNode) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *ColumnNode) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *ColumnNode) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ColumnNode) GetOperators() []*node.Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type ScannerNode struct {
	Table                *node.Table      `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Expressions          []*Node          `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	From                 *Node            `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Operators            []*node.Operator `protobuf:"bytes,4,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ScannerNode) Reset()         { *m = ScannerNode{} }
func (m *ScannerNode) String() string { return proto.CompactTextString(m) }
func (*ScannerNode) ProtoMessage()    {}
func (*ScannerNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{2}
}
func (m *ScannerNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScannerNode.Unmarshal(m, b)
}
func (m *ScannerNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScannerNode.Marshal(b, m, deterministic)
}
func (m *ScannerNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScannerNode.Merge(m, src)
}
func (m *ScannerNode) XXX_Size() int {
	return xxx_messageInfo_ScannerNode.Size(m)
}
func (m *ScannerNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ScannerNode.DiscardUnknown(m)
}

var xxx_messageInfo_ScannerNode proto.InternalMessageInfo

func (m *ScannerNode) GetTable() *node.Table {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *ScannerNode) GetExpressions() []*Node {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *ScannerNode) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *ScannerNode) GetOperators() []*node.Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type FilterNode struct {
	Conditions           *Node    `protobuf:"bytes,1,opt,name=conditions,proto3" json:"conditions,omitempty"`
	From                 *Node    `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterNode) Reset()         { *m = FilterNode{} }
func (m *FilterNode) String() string { return proto.CompactTextString(m) }
func (*FilterNode) ProtoMessage()    {}
func (*FilterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{3}
}
func (m *FilterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterNode.Unmarshal(m, b)
}
func (m *FilterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterNode.Marshal(b, m, deterministic)
}
func (m *FilterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterNode.Merge(m, src)
}
func (m *FilterNode) XXX_Size() int {
	return xxx_messageInfo_FilterNode.Size(m)
}
func (m *FilterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterNode.DiscardUnknown(m)
}

var xxx_messageInfo_FilterNode proto.InternalMessageInfo

func (m *FilterNode) GetConditions() *Node {
	if m != nil {
		return m.Conditions
	}
	return nil
}

func (m *FilterNode) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

type FunctionNode struct {
	Expressions          []*Node  `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Distinct             bool     `protobuf:"varint,3,opt,name=distinct,proto3" json:"distinct,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FunctionNode) Reset()         { *m = FunctionNode{} }
func (m *FunctionNode) String() string { return proto.CompactTextString(m) }
func (*FunctionNode) ProtoMessage()    {}
func (*FunctionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{4}
}
func (m *FunctionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FunctionNode.Unmarshal(m, b)
}
func (m *FunctionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FunctionNode.Marshal(b, m, deterministic)
}
func (m *FunctionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FunctionNode.Merge(m, src)
}
func (m *FunctionNode) XXX_Size() int {
	return xxx_messageInfo_FunctionNode.Size(m)
}
func (m *FunctionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_FunctionNode.DiscardUnknown(m)
}

var xxx_messageInfo_FunctionNode proto.InternalMessageInfo

func (m *FunctionNode) GetExpressions() []*Node {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *FunctionNode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionNode) GetDistinct() bool {
	if m != nil {
		return m.Distinct
	}
	return false
}

type AggregationNode struct {
	From                 *Node    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	GroupBy              []*Node  `protobuf:"bytes,2,rep,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	Having               *Node    `protobuf:"bytes,3,opt,name=having,proto3" json:"having,omitempty"`
	Expressions          []*Node  `protobuf:"bytes,4,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AggregationNode) Reset()         { *m = AggregationNode{} }
func (m *AggregationNode) String() string { return proto.CompactTextString(m) }
func (*AggregationNode) ProtoMessage()    {}
func (*AggregationNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{5}
}
func (m *AggregationNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregationNode.Unmarshal(m, b)
}
func (m *AggregationNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregationNode.Marshal(b, m, deterministic)
}
func (m *AggregationNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregationNode.Merge(m, src)
}
func (m *AggregationNode) XXX_Size() int {
	return xxx_messageInfo_AggregationNode.Size(m)
}
func (m *AggregationNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregationNode.DiscardUnknown(m)
}

var xxx_messageInfo_AggregationNode proto.InternalMessageInfo

func (m *AggregationNode) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *AggregationNode) GetGroupBy() []*Node {
	if m != nil {
		return m.GroupBy
	}
	return nil
}

func (m *AggregationNode) GetHaving() *Node {
	if m != nil {
		return m.Having
	}
	return nil
}

func (m *AggregationNode) GetExpressions() []*Node {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type AndExpressionNode struct {
	Left                 *Node    `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                *Node    `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AndExpressionNode) Reset()         { *m = AndExpressionNode{} }
func (m *AndExpressionNode) String() string { return proto.CompactTextString(m) }
func (*AndExpressionNode) ProtoMessage()    {}
func (*AndExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{6}
}
func (m *AndExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AndExpressionNode.Unmarshal(m, b)
}
func (m *AndExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AndExpressionNode.Marshal(b, m, deterministic)
}
func (m *AndExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AndExpressionNode.Merge(m, src)
}
func (m *AndExpressionNode) XXX_Size() int {
	return xxx_messageInfo_AndExpressionNode.Size(m)
}
func (m *AndExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_AndExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_AndExpressionNode proto.InternalMessageInfo

func (m *AndExpressionNode) GetLeft() *Node {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *AndExpressionNode) GetRight() *Node {
	if m != nil {
		return m.Right
	}
	return nil
}

type OrExpressionNode struct {
	Left                 *Node    `protobuf:"bytes,1,opt,name=left,proto3" json:"left,omitempty"`
	Right                *Node    `protobuf:"bytes,2,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrExpressionNode) Reset()         { *m = OrExpressionNode{} }
func (m *OrExpressionNode) String() string { return proto.CompactTextString(m) }
func (*OrExpressionNode) ProtoMessage()    {}
func (*OrExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{7}
}
func (m *OrExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrExpressionNode.Unmarshal(m, b)
}
func (m *OrExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrExpressionNode.Marshal(b, m, deterministic)
}
func (m *OrExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrExpressionNode.Merge(m, src)
}
func (m *OrExpressionNode) XXX_Size() int {
	return xxx_messageInfo_OrExpressionNode.Size(m)
}
func (m *OrExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_OrExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_OrExpressionNode proto.InternalMessageInfo

func (m *OrExpressionNode) GetLeft() *Node {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *OrExpressionNode) GetRight() *Node {
	if m != nil {
		return m.Right
	}
	return nil
}

type BinaryExpressionNode struct {
	Operator             node.BinaryStatement `protobuf:"varint,1,opt,name=operator,proto3,enum=cloudproud.lunodb.node.v1.BinaryStatement" json:"operator,omitempty"`
	Left                 *Node                `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                *Node                `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BinaryExpressionNode) Reset()         { *m = BinaryExpressionNode{} }
func (m *BinaryExpressionNode) String() string { return proto.CompactTextString(m) }
func (*BinaryExpressionNode) ProtoMessage()    {}
func (*BinaryExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{8}
}
func (m *BinaryExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BinaryExpressionNode.Unmarshal(m, b)
}
func (m *BinaryExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BinaryExpressionNode.Marshal(b, m, deterministic)
}
func (m *BinaryExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BinaryExpressionNode.Merge(m, src)
}
func (m *BinaryExpressionNode) XXX_Size() int {
	return xxx_messageInfo_BinaryExpressionNode.Size(m)
}
func (m *BinaryExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_BinaryExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_BinaryExpressionNode proto.InternalMessageInfo

func (m *BinaryExpressionNode) GetOperator() node.BinaryStatement {
	if m != nil {
		return m.Operator
	}
	return node.BinaryStatementUnknown
}

func (m *BinaryExpressionNode) GetLeft() *Node {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *BinaryExpressionNode) GetRight() *Node {
	if m != nil {
		return m.Right
	}
	return nil
}

type CastExpression struct {
	Type                 *types.Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Expression           *Node       `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CastExpression) Reset()         { *m = CastExpression{} }
func (m *CastExpression) String() string { return proto.CompactTextString(m) }
func (*CastExpression) ProtoMessage()    {}
func (*CastExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{9}
}
func (m *CastExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CastExpression.Unmarshal(m, b)
}
func (m *CastExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CastExpression.Marshal(b, m, deterministic)
}
func (m *CastExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CastExpression.Merge(m, src)
}
func (m *CastExpression) XXX_Size() int {
	return xxx_messageInfo_CastExpression.Size(m)
}
func (m *CastExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_CastExpression.DiscardUnknown(m)
}

var xxx_messageInfo_CastExpression proto.InternalMessageInfo

func (m *CastExpression) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *CastExpression) GetExpression() *Node {
	if m != nil {
		return m.Expression
	}
	return nil
}

type ComparisonExpressionNode struct {
	Operator             node.OperatorStatement `protobuf:"varint,1,opt,name=operator,proto3,enum=cloudproud.lunodb.node.v1.OperatorStatement" json:"operator,omitempty"`
	Left                 *Node                  `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	Right                *Node                  `protobuf:"bytes,3,opt,name=right,proto3" json:"right,omitempty"`
	SubOperator          node.OperatorStatement `protobuf:"varint,4,opt,name=sub_operator,json=subOperator,proto3,enum=cloudproud.lunodb.node.v1.OperatorStatement" json:"sub_operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ComparisonExpressionNode) Reset()         { *m = ComparisonExpressionNode{} }
func (m *ComparisonExpressionNode) String() string { return proto.CompactTextString(m) }
func (*ComparisonExpressionNode) ProtoMessage()    {}
func (*ComparisonExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{10}
}
func (m *ComparisonExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComparisonExpressionNode.Unmarshal(m, b)
}
func (m *ComparisonExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComparisonExpressionNode.Marshal(b, m, deterministic)
}
func (m *ComparisonExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComparisonExpressionNode.Merge(m, src)
}
func (m *ComparisonExpressionNode) XXX_Size() int {
	return xxx_messageInfo_ComparisonExpressionNode.Size(m)
}
func (m *ComparisonExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ComparisonExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_ComparisonExpressionNode proto.InternalMessageInfo

func (m *ComparisonExpressionNode) GetOperator() node.OperatorStatement {
	if m != nil {
		return m.Operator
	}
	return node.OperatorUnknown
}

func (m *ComparisonExpressionNode) GetLeft() *Node {
	if m != nil {
		return m.Left
	}
	return nil
}

func (m *ComparisonExpressionNode) GetRight() *Node {
	if m != nil {
		return m.Right
	}
	return nil
}

func (m *ComparisonExpressionNode) GetSubOperator() node.OperatorStatement {
	if m != nil {
		return m.SubOperator
	}
	return node.OperatorUnknown
}

type CaseExpressionNode struct {
	Expression           *Node                 `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	When                 []*WhenExpressionNode `protobuf:"bytes,2,rep,name=when,proto3" json:"when,omitempty"`
	Else                 *Node                 `protobuf:"bytes,3,opt,name=else,proto3" json:"else,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CaseExpressionNode) Reset()         { *m = CaseExpressionNode{} }
func (m *CaseExpressionNode) String() string { return proto.CompactTextString(m) }
func (*CaseExpressionNode) ProtoMessage()    {}
func (*CaseExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{11}
}
func (m *CaseExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CaseExpressionNode.Unmarshal(m, b)
}
func (m *CaseExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CaseExpressionNode.Marshal(b, m, deterministic)
}
func (m *CaseExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CaseExpressionNode.Merge(m, src)
}
func (m *CaseExpressionNode) XXX_Size() int {
	return xxx_messageInfo_CaseExpressionNode.Size(m)
}
func (m *CaseExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_CaseExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_CaseExpressionNode proto.InternalMessageInfo

func (m *CaseExpressionNode) GetExpression() *Node {
	if m != nil {
		return m.Expression
	}
	return nil
}

func (m *CaseExpressionNode) GetWhen() []*WhenExpressionNode {
	if m != nil {
		return m.When
	}
	return nil
}

func (m *CaseExpressionNode) GetElse() *Node {
	if m != nil {
		return m.Else
	}
	return nil
}

type WhenExpressionNode struct {
	Condition            *Node    `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Value                *Node    `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WhenExpressionNode) Reset()         { *m = WhenExpressionNode{} }
func (m *WhenExpressionNode) String() string { return proto.CompactTextString(m) }
func (*WhenExpressionNode) ProtoMessage()    {}
func (*WhenExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{12}
}
func (m *WhenExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WhenExpressionNode.Unmarshal(m, b)
}
func (m *WhenExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WhenExpressionNode.Marshal(b, m, deterministic)
}
func (m *WhenExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhenExpressionNode.Merge(m, src)
}
func (m *WhenExpressionNode) XXX_Size() int {
	return xxx_messageInfo_WhenExpressionNode.Size(m)
}
func (m *WhenExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_WhenExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_WhenExpressionNode proto.InternalMessageInfo

func (m *WhenExpressionNode) GetCondition() *Node {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *WhenExpressionNode) GetValue() *Node {
	if m != nil {
		return m.Value
	}
	return nil
}

type ConstantNode struct {
	Type                 *types.Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Value                []byte      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConstantNode) Reset()         { *m = ConstantNode{} }
func (m *ConstantNode) String() string { return proto.CompactTextString(m) }
func (*ConstantNode) ProtoMessage()    {}
func (*ConstantNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{13}
}
func (m *ConstantNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConstantNode.Unmarshal(m, b)
}
func (m *ConstantNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConstantNode.Marshal(b, m, deterministic)
}
func (m *ConstantNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConstantNode.Merge(m, src)
}
func (m *ConstantNode) XXX_Size() int {
	return xxx_messageInfo_ConstantNode.Size(m)
}
func (m *ConstantNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ConstantNode.DiscardUnknown(m)
}

var xxx_messageInfo_ConstantNode proto.InternalMessageInfo

func (m *ConstantNode) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ConstantNode) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type OrderByNode struct {
	From                 *Node                  `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Expressions          []*OrderExpressionNode `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *OrderByNode) Reset()         { *m = OrderByNode{} }
func (m *OrderByNode) String() string { return proto.CompactTextString(m) }
func (*OrderByNode) ProtoMessage()    {}
func (*OrderByNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{14}
}
func (m *OrderByNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderByNode.Unmarshal(m, b)
}
func (m *OrderByNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderByNode.Marshal(b, m, deterministic)
}
func (m *OrderByNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderByNode.Merge(m, src)
}
func (m *OrderByNode) XXX_Size() int {
	return xxx_messageInfo_OrderByNode.Size(m)
}
func (m *OrderByNode) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderByNode.DiscardUnknown(m)
}

var xxx_messageInfo_OrderByNode proto.InternalMessageInfo

func (m *OrderByNode) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *OrderByNode) GetExpressions() []*OrderExpressionNode {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type OrderExpressionNode struct {
	Direction            uint32   `protobuf:"varint,1,opt,name=direction,proto3" json:"direction,omitempty"`
	Expression           *Node    `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderExpressionNode) Reset()         { *m = OrderExpressionNode{} }
func (m *OrderExpressionNode) String() string { return proto.CompactTextString(m) }
func (*OrderExpressionNode) ProtoMessage()    {}
func (*OrderExpressionNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{15}
}
func (m *OrderExpressionNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderExpressionNode.Unmarshal(m, b)
}
func (m *OrderExpressionNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderExpressionNode.Marshal(b, m, deterministic)
}
func (m *OrderExpressionNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderExpressionNode.Merge(m, src)
}
func (m *OrderExpressionNode) XXX_Size() int {
	return xxx_messageInfo_OrderExpressionNode.Size(m)
}
func (m *OrderExpressionNode) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderExpressionNode.DiscardUnknown(m)
}

var xxx_messageInfo_OrderExpressionNode proto.InternalMessageInfo

func (m *OrderExpressionNode) GetDirection() uint32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *OrderExpressionNode) GetExpression() *Node {
	if m != nil {
		return m.Expression
	}
	return nil
}

type TupleNode struct {
	Expressions          []*Node  `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TupleNode) Reset()         { *m = TupleNode{} }
func (m *TupleNode) String() string { return proto.CompactTextString(m) }
func (*TupleNode) ProtoMessage()    {}
func (*TupleNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{16}
}
func (m *TupleNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TupleNode.Unmarshal(m, b)
}
func (m *TupleNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TupleNode.Marshal(b, m, deterministic)
}
func (m *TupleNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TupleNode.Merge(m, src)
}
func (m *TupleNode) XXX_Size() int {
	return xxx_messageInfo_TupleNode.Size(m)
}
func (m *TupleNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TupleNode.DiscardUnknown(m)
}

var xxx_messageInfo_TupleNode proto.InternalMessageInfo

func (m *TupleNode) GetExpressions() []*Node {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type VariableExpression struct {
	Offset               uint64      `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Type                 *types.Type `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VariableExpression) Reset()         { *m = VariableExpression{} }
func (m *VariableExpression) String() string { return proto.CompactTextString(m) }
func (*VariableExpression) ProtoMessage()    {}
func (*VariableExpression) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{17}
}
func (m *VariableExpression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariableExpression.Unmarshal(m, b)
}
func (m *VariableExpression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariableExpression.Marshal(b, m, deterministic)
}
func (m *VariableExpression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariableExpression.Merge(m, src)
}
func (m *VariableExpression) XXX_Size() int {
	return xxx_messageInfo_VariableExpression.Size(m)
}
func (m *VariableExpression) XXX_DiscardUnknown() {
	xxx_messageInfo_VariableExpression.DiscardUnknown(m)
}

var xxx_messageInfo_VariableExpression proto.InternalMessageInfo

func (m *VariableExpression) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *VariableExpression) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type ValuesClauseNode struct {
	Rows                 []*Expressions `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ValuesClauseNode) Reset()         { *m = ValuesClauseNode{} }
func (m *ValuesClauseNode) String() string { return proto.CompactTextString(m) }
func (*ValuesClauseNode) ProtoMessage()    {}
func (*ValuesClauseNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{18}
}
func (m *ValuesClauseNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValuesClauseNode.Unmarshal(m, b)
}
func (m *ValuesClauseNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValuesClauseNode.Marshal(b, m, deterministic)
}
func (m *ValuesClauseNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValuesClauseNode.Merge(m, src)
}
func (m *ValuesClauseNode) XXX_Size() int {
	return xxx_messageInfo_ValuesClauseNode.Size(m)
}
func (m *ValuesClauseNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ValuesClauseNode.DiscardUnknown(m)
}

var xxx_messageInfo_ValuesClauseNode proto.InternalMessageInfo

func (m *ValuesClauseNode) GetRows() []*Expressions {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Expressions struct {
	Expressions          []*Node  `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Expressions) Reset()         { *m = Expressions{} }
func (m *Expressions) String() string { return proto.CompactTextString(m) }
func (*Expressions) ProtoMessage()    {}
func (*Expressions) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{19}
}
func (m *Expressions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expressions.Unmarshal(m, b)
}
func (m *Expressions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expressions.Marshal(b, m, deterministic)
}
func (m *Expressions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expressions.Merge(m, src)
}
func (m *Expressions) XXX_Size() int {
	return xxx_messageInfo_Expressions.Size(m)
}
func (m *Expressions) XXX_DiscardUnknown() {
	xxx_messageInfo_Expressions.DiscardUnknown(m)
}

var xxx_messageInfo_Expressions proto.InternalMessageInfo

func (m *Expressions) GetExpressions() []*Node {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type ParameterNode struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParameterNode) Reset()         { *m = ParameterNode{} }
func (m *ParameterNode) String() string { return proto.CompactTextString(m) }
func (*ParameterNode) ProtoMessage()    {}
func (*ParameterNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{20}
}
func (m *ParameterNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParameterNode.Unmarshal(m, b)
}
func (m *ParameterNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParameterNode.Marshal(b, m, deterministic)
}
func (m *ParameterNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParameterNode.Merge(m, src)
}
func (m *ParameterNode) XXX_Size() int {
	return xxx_messageInfo_ParameterNode.Size(m)
}
func (m *ParameterNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ParameterNode.DiscardUnknown(m)
}

var xxx_messageInfo_ParameterNode proto.InternalMessageInfo

func (m *ParameterNode) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type DistinctNode struct {
	From                 *Node    `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Expressions          []*Node  `protobuf:"bytes,2,rep,name=expressions,proto3" json:"expressions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistinctNode) Reset()         { *m = DistinctNode{} }
func (m *DistinctNode) String() string { return proto.CompactTextString(m) }
func (*DistinctNode) ProtoMessage()    {}
func (*DistinctNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{21}
}
func (m *DistinctNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistinctNode.Unmarshal(m, b)
}
func (m *DistinctNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistinctNode.Marshal(b, m, deterministic)
}
func (m *DistinctNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistinctNode.Merge(m, src)
}
func (m *DistinctNode) XXX_Size() int {
	return xxx_messageInfo_DistinctNode.Size(m)
}
func (m *DistinctNode) XXX_DiscardUnknown() {
	xxx_messageInfo_DistinctNode.DiscardUnknown(m)
}

var xxx_messageInfo_DistinctNode proto.InternalMessageInfo

func (m *DistinctNode) GetFrom() *Node {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *DistinctNode) GetExpressions() []*Node {
	if m != nil {
		return m.Expressions
	}
	return nil
}

type RecordNode struct {
	Columns              []*Node  `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecordNode) Reset()         { *m = RecordNode{} }
func (m *RecordNode) String() string { return proto.CompactTextString(m) }
func (*RecordNode) ProtoMessage()    {}
func (*RecordNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{22}
}
func (m *RecordNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordNode.Unmarshal(m, b)
}
func (m *RecordNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordNode.Marshal(b, m, deterministic)
}
func (m *RecordNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordNode.Merge(m, src)
}
func (m *RecordNode) XXX_Size() int {
	return xxx_messageInfo_RecordNode.Size(m)
}
func (m *RecordNode) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordNode.DiscardUnknown(m)
}

var xxx_messageInfo_RecordNode proto.InternalMessageInfo

func (m *RecordNode) GetColumns() []*Node {
	if m != nil {
		return m.Columns
	}
	return nil
}

type ReferenceNode struct {
	Parts                []string `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
	Node                 *Node    `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReferenceNode) Reset()         { *m = ReferenceNode{} }
func (m *ReferenceNode) String() string { return proto.CompactTextString(m) }
func (*ReferenceNode) ProtoMessage()    {}
func (*ReferenceNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{23}
}
func (m *ReferenceNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferenceNode.Unmarshal(m, b)
}
func (m *ReferenceNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferenceNode.Marshal(b, m, deterministic)
}
func (m *ReferenceNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferenceNode.Merge(m, src)
}
func (m *ReferenceNode) XXX_Size() int {
	return xxx_messageInfo_ReferenceNode.Size(m)
}
func (m *ReferenceNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferenceNode.DiscardUnknown(m)
}

var xxx_messageInfo_ReferenceNode proto.InternalMessageInfo

func (m *ReferenceNode) GetParts() []string {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *ReferenceNode) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type ValueNode struct {
	Type                 *types.Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ValueNode) Reset()         { *m = ValueNode{} }
func (m *ValueNode) String() string { return proto.CompactTextString(m) }
func (*ValueNode) ProtoMessage()    {}
func (*ValueNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_91877109aacab46f, []int{24}
}
func (m *ValueNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValueNode.Unmarshal(m, b)
}
func (m *ValueNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValueNode.Marshal(b, m, deterministic)
}
func (m *ValueNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValueNode.Merge(m, src)
}
func (m *ValueNode) XXX_Size() int {
	return xxx_messageInfo_ValueNode.Size(m)
}
func (m *ValueNode) XXX_DiscardUnknown() {
	xxx_messageInfo_ValueNode.DiscardUnknown(m)
}

var xxx_messageInfo_ValueNode proto.InternalMessageInfo

func (m *ValueNode) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func init() {
	proto.RegisterType((*Node)(nil), "cloudproud.lunodb.connector.plan.v1.Node")
	proto.RegisterType((*ColumnNode)(nil), "cloudproud.lunodb.connector.plan.v1.ColumnNode")
	proto.RegisterType((*ScannerNode)(nil), "cloudproud.lunodb.connector.plan.v1.ScannerNode")
	proto.RegisterType((*FilterNode)(nil), "cloudproud.lunodb.connector.plan.v1.FilterNode")
	proto.RegisterType((*FunctionNode)(nil), "cloudproud.lunodb.connector.plan.v1.FunctionNode")
	proto.RegisterType((*AggregationNode)(nil), "cloudproud.lunodb.connector.plan.v1.AggregationNode")
	proto.RegisterType((*AndExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.AndExpressionNode")
	proto.RegisterType((*OrExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.OrExpressionNode")
	proto.RegisterType((*BinaryExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.BinaryExpressionNode")
	proto.RegisterType((*CastExpression)(nil), "cloudproud.lunodb.connector.plan.v1.CastExpression")
	proto.RegisterType((*ComparisonExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.ComparisonExpressionNode")
	proto.RegisterType((*CaseExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.CaseExpressionNode")
	proto.RegisterType((*WhenExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.WhenExpressionNode")
	proto.RegisterType((*ConstantNode)(nil), "cloudproud.lunodb.connector.plan.v1.ConstantNode")
	proto.RegisterType((*OrderByNode)(nil), "cloudproud.lunodb.connector.plan.v1.OrderByNode")
	proto.RegisterType((*OrderExpressionNode)(nil), "cloudproud.lunodb.connector.plan.v1.OrderExpressionNode")
	proto.RegisterType((*TupleNode)(nil), "cloudproud.lunodb.connector.plan.v1.TupleNode")
	proto.RegisterType((*VariableExpression)(nil), "cloudproud.lunodb.connector.plan.v1.VariableExpression")
	proto.RegisterType((*ValuesClauseNode)(nil), "cloudproud.lunodb.connector.plan.v1.ValuesClauseNode")
	proto.RegisterType((*Expressions)(nil), "cloudproud.lunodb.connector.plan.v1.Expressions")
	proto.RegisterType((*ParameterNode)(nil), "cloudproud.lunodb.connector.plan.v1.ParameterNode")
	proto.RegisterType((*DistinctNode)(nil), "cloudproud.lunodb.connector.plan.v1.DistinctNode")
	proto.RegisterType((*RecordNode)(nil), "cloudproud.lunodb.connector.plan.v1.RecordNode")
	proto.RegisterType((*ReferenceNode)(nil), "cloudproud.lunodb.connector.plan.v1.ReferenceNode")
	proto.RegisterType((*ValueNode)(nil), "cloudproud.lunodb.connector.plan.v1.ValueNode")
}

func init() { proto.RegisterFile("proto/plan/plan.proto", fileDescriptor_91877109aacab46f) }

var fileDescriptor_91877109aacab46f = []byte{
	// 1407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x58, 0x4d, 0x6f, 0x1b, 0x45,
	0x1f, 0xef, 0x6e, 0x36, 0x8e, 0xfd, 0xb7, 0x9d, 0xb6, 0xd3, 0xb4, 0xcf, 0x3e, 0x55, 0xa5, 0x46,
	0x5b, 0x3d, 0x6a, 0x9f, 0xe7, 0x41, 0x0e, 0x49, 0x4b, 0x01, 0x4b, 0x15, 0x8a, 0x1d, 0xfa, 0xa2,
	0xb6, 0x24, 0x6c, 0x4b, 0xa8, 0xa2, 0x88, 0x68, 0xbc, 0x3b, 0xb6, 0x57, 0x5a, 0xcf, 0xac, 0x66,
	0xc7, 0x69, 0x73, 0xe1, 0xc0, 0x95, 0x13, 0x05, 0x71, 0xe0, 0xc0, 0x81, 0x03, 0x42, 0xdc, 0xf9,
	0x12, 0xdc, 0xf8, 0x02, 0x3d, 0xf4, 0x08, 0x5f, 0x02, 0xcd, 0xec, 0xab, 0xed, 0x50, 0xed, 0x3a,
	0x91, 0xe0, 0x62, 0x79, 0xc6, 0xf3, 0xfb, 0xfd, 0xdf, 0x66, 0xfe, 0x2f, 0x86, 0x8b, 0x01, 0x67,
	0x82, 0xad, 0x05, 0x3e, 0xa6, 0xea, 0xa3, 0xa5, 0xd6, 0xe8, 0x9a, 0xe3, 0xb3, 0xb1, 0x1b, 0x70,
	0x36, 0x76, 0x5b, 0xfe, 0x98, 0x32, 0xb7, 0xd7, 0x72, 0x18, 0xa5, 0xc4, 0x11, 0x8c, 0xb7, 0xd4,
	0xb9, 0xc3, 0xf5, 0xcb, 0x2b, 0x03, 0x36, 0x60, 0x11, 0x5e, 0x7e, 0x8b, 0xa0, 0x97, 0x63, 0x46,
	0xca, 0x5c, 0xa2, 0x3e, 0xe2, 0xed, 0x7f, 0x45, 0xdb, 0xe2, 0x28, 0x20, 0x61, 0xf4, 0x19, 0xfd,
	0x60, 0xfd, 0xd6, 0x04, 0xe3, 0x23, 0xe6, 0x12, 0xf4, 0x08, 0x96, 0x42, 0x07, 0x53, 0x4a, 0xb8,
	0xa9, 0xad, 0x6a, 0x37, 0xea, 0x1b, 0x6f, 0xb7, 0x0a, 0x68, 0xd1, 0x7a, 0x12, 0x61, 0x24, 0xc5,
	0xfd, 0x33, 0x76, 0x42, 0x81, 0x1e, 0x40, 0xc5, 0x61, 0xfe, 0x78, 0x44, 0x4d, 0x5d, 0x91, 0xad,
	0x15, 0x22, 0xeb, 0x2a, 0x48, 0xcc, 0x15, 0x13, 0x48, 0xaa, 0xbe, 0xe7, 0x0b, 0xc2, 0xcd, 0x85,
	0x12, 0x54, 0x77, 0x15, 0x24, 0xa1, 0x8a, 0x08, 0xd0, 0x36, 0x54, 0xfb, 0x63, 0xea, 0x08, 0x8f,
	0x51, 0xd3, 0x50, 0x64, 0xeb, 0xc5, 0xc8, 0x62, 0x50, 0x4c, 0x97, 0x92, 0xa0, 0x67, 0x50, 0xc7,
	0x83, 0x01, 0x27, 0x03, 0xac, 0x38, 0x17, 0x15, 0xe7, 0xad, 0x42, 0x9c, 0x9b, 0x19, 0x2e, 0xa6,
	0xcd, 0x53, 0xa1, 0x03, 0x58, 0xc6, 0xd4, 0x3d, 0x20, 0x2f, 0x02, 0x4e, 0xc2, 0x50, 0x92, 0x2f,
	0x29, 0xf2, 0xdb, 0xc5, 0xc8, 0xa9, 0xfb, 0x61, 0x8a, 0x8c, 0xe9, 0x9b, 0x38, 0xbf, 0x89, 0xf6,
	0xa1, 0xc9, 0x78, 0x9e, 0xbf, 0xaa, 0xf8, 0xdf, 0x29, 0xc4, 0xbf, 0xcd, 0x67, 0xe8, 0x1b, 0x2c,
	0xb7, 0x87, 0x04, 0x5c, 0x74, 0xd8, 0x28, 0xc0, 0xdc, 0x0b, 0x19, 0xcd, 0x4b, 0xa9, 0x29, 0x29,
	0x77, 0x0a, 0x5e, 0x87, 0x84, 0x61, 0x46, 0xda, 0x8a, 0x73, 0xcc, 0x6f, 0x68, 0x08, 0xe7, 0x7b,
	0x1e, 0xc5, 0xfc, 0x28, 0x2f, 0x11, 0x94, 0xc4, 0xf7, 0x0b, 0x49, 0xec, 0x28, 0xf4, 0x8c, 0xb4,
	0x73, 0xbd, 0xa9, 0x7d, 0xf4, 0x19, 0x9c, 0x75, 0x70, 0x28, 0xf2, 0x72, 0xea, 0x4a, 0xce, 0xcd,
	0x62, 0x96, 0xe1, 0x50, 0x64, 0x6c, 0xf7, 0xcf, 0xd8, 0xcb, 0xce, 0xc4, 0x0e, 0xea, 0x29, 0x7e,
	0x92, 0xe7, 0x6f, 0x28, 0xfe, 0x77, 0x8b, 0xf2, 0x93, 0x19, 0x2b, 0xa4, 0x8c, 0xdc, 0xae, 0x7c,
	0x0d, 0x0e, 0xa3, 0xa1, 0xc0, 0x54, 0x98, 0xcd, 0x12, 0xaf, 0xa1, 0x1b, 0x83, 0x92, 0xd7, 0x90,
	0x90, 0xa0, 0xbb, 0xb0, 0x28, 0xc6, 0x81, 0x4f, 0x4c, 0xa4, 0xd8, 0x5a, 0x85, 0xd8, 0x9e, 0x4a,
	0x44, 0x4c, 0x15, 0xc1, 0xd1, 0x27, 0x50, 0x3d, 0xc4, 0xdc, 0xc3, 0x3d, 0x9f, 0x98, 0x17, 0x4a,
	0x58, 0xbd, 0x1b, 0x83, 0x26, 0x3c, 0x9b, 0x52, 0xa1, 0xc7, 0x50, 0x65, 0xdc, 0x25, 0xfc, 0xa0,
	0x77, 0x64, 0xae, 0x94, 0x48, 0x71, 0xdb, 0x12, 0xd4, 0x39, 0x4a, 0x52, 0x1c, 0x8b, 0x96, 0x68,
	0x1b, 0x2a, 0x87, 0xd8, 0x1f, 0x93, 0xd0, 0xbc, 0x58, 0xe2, 0xe5, 0xec, 0x2a, 0x48, 0xd7, 0xc7,
	0xe3, 0x30, 0xb1, 0x3a, 0xa6, 0x41, 0x36, 0xd4, 0x02, 0xcc, 0xf1, 0x88, 0xc8, 0x5c, 0xf7, 0x6f,
	0xc5, 0xb9, 0x51, 0x88, 0x73, 0x27, 0x41, 0xc5, 0x84, 0x19, 0x8d, 0x8c, 0xb1, 0xeb, 0x85, 0xc2,
	0xa3, 0x8e, 0x30, 0xaf, 0x94, 0x88, 0xf1, 0x56, 0x0c, 0x4a, 0x62, 0x9c, 0x90, 0x48, 0x25, 0x39,
	0xe9, 0x13, 0x4e, 0xa8, 0x43, 0xcc, 0xab, 0x25, 0x94, 0xb4, 0x13, 0x54, 0xa2, 0x64, 0x4a, 0x23,
	0xef, 0x8d, 0x72, 0x81, 0xb9, 0x5a, 0xe2, 0xde, 0x28, 0x47, 0x26, 0xf7, 0x46, 0xc1, 0x3b, 0x15,
	0x30, 0xe4, 0xaf, 0xd6, 0x17, 0x3a, 0x40, 0x56, 0x4a, 0xd0, 0x25, 0xd0, 0x3d, 0x57, 0x15, 0x35,
	0xa3, 0x53, 0x79, 0xfd, 0xea, 0xaa, 0xfe, 0x60, 0xcb, 0xd6, 0x3d, 0x17, 0x21, 0x30, 0x28, 0x1e,
	0x11, 0x55, 0xa1, 0x6a, 0xb6, 0xfa, 0x8e, 0x56, 0x60, 0x51, 0xa8, 0x7b, 0xb7, 0xa0, 0x36, 0xa3,
	0x05, 0xba, 0x04, 0x95, 0xd0, 0x19, 0x92, 0x11, 0x56, 0x55, 0xa3, 0x66, 0xc7, 0x2b, 0x64, 0xc2,
	0x92, 0x83, 0x05, 0xf6, 0xd9, 0x40, 0xa5, 0xfe, 0x9a, 0x9d, 0x2c, 0xd1, 0x1d, 0x30, 0x64, 0xf5,
	0x35, 0x2b, 0xca, 0xa2, 0xff, 0x16, 0xb2, 0x48, 0x2a, 0x6b, 0x2b, 0x18, 0xda, 0x84, 0x1a, 0x0b,
	0x08, 0xc7, 0x82, 0xf1, 0xd0, 0x5c, 0x5a, 0x5d, 0xb8, 0x51, 0xdf, 0xb8, 0x76, 0x0c, 0x87, 0x2a,
	0xf0, 0xf2, 0x86, 0xc6, 0x67, 0xed, 0x0c, 0x65, 0x7d, 0xa3, 0x43, 0x3d, 0x57, 0x9c, 0xd1, 0xed,
	0xc4, 0xb2, 0xa8, 0xba, 0xaf, 0xbe, 0x81, 0xee, 0xa9, 0x3c, 0x97, 0xd8, 0xfe, 0x10, 0xea, 0x59,
	0x12, 0x0a, 0x4d, 0x5d, 0x29, 0x53, 0xc2, 0xa0, 0x3c, 0x5a, 0xba, 0xa5, 0xcf, 0xd9, 0x28, 0xae,
	0xe4, 0x65, 0xdc, 0x22, 0x61, 0x93, 0x6e, 0x31, 0xe6, 0x72, 0xcb, 0xb7, 0x1a, 0x40, 0xd6, 0x1b,
	0xa0, 0x07, 0x00, 0x0e, 0xa3, 0xae, 0x27, 0x94, 0x71, 0x5a, 0x59, 0xb5, 0x72, 0xe0, 0xd4, 0x36,
	0x7d, 0x2e, 0xdb, 0xac, 0x2f, 0x35, 0x68, 0xe4, 0xfb, 0x8c, 0x69, 0xc7, 0x6b, 0x27, 0x72, 0xfc,
	0x71, 0x77, 0xfd, 0x72, 0x2e, 0x37, 0xc8, 0x80, 0x54, 0xb3, 0x67, 0x6e, 0xfd, 0xa8, 0xc3, 0xd9,
	0xa9, 0x0e, 0x25, 0x35, 0x50, 0x9b, 0x2f, 0x78, 0x5b, 0x50, 0x1d, 0x70, 0x36, 0x0e, 0x64, 0xfa,
	0x2d, 0x7d, 0x8b, 0x96, 0x14, 0xb4, 0x73, 0x84, 0x36, 0xa1, 0x32, 0xc4, 0x87, 0x1e, 0x1d, 0x94,
	0xbf, 0x43, 0x31, 0x70, 0xda, 0xb1, 0xc6, 0x49, 0x1c, 0x6b, 0x7d, 0xad, 0xc1, 0xf9, 0x99, 0x6e,
	0x4b, 0xba, 0xca, 0x27, 0x7d, 0x31, 0x87, 0xab, 0x24, 0x0c, 0x7d, 0x00, 0x8b, 0xdc, 0x1b, 0x0c,
	0x45, 0xf9, 0xbb, 0x14, 0xe1, 0xac, 0x97, 0x1a, 0x9c, 0x9b, 0xee, 0xd1, 0xfe, 0x76, 0xa5, 0x5e,
	0x69, 0xb0, 0x72, 0x5c, 0x83, 0x85, 0xee, 0x42, 0x35, 0x79, 0xa0, 0x4a, 0xb9, 0xe5, 0x8d, 0xff,
	0xbd, 0xe1, 0x55, 0x47, 0x14, 0x4f, 0x04, 0x16, 0x64, 0x44, 0xa8, 0xb0, 0x53, 0x6c, 0x6a, 0xa0,
	0x7e, 0x42, 0x03, 0x17, 0xe6, 0x34, 0xf0, 0x2b, 0x0d, 0x96, 0x27, 0x3b, 0x3b, 0x74, 0x0b, 0x0c,
	0x39, 0x6d, 0xbd, 0x21, 0xe9, 0x46, 0xc3, 0x98, 0xcc, 0xba, 0x47, 0x01, 0xb1, 0xd5, 0x69, 0x99,
	0x95, 0x72, 0x8d, 0x5f, 0x69, 0x73, 0x72, 0x60, 0xeb, 0x17, 0x1d, 0xcc, 0xbf, 0xea, 0xa3, 0xd1,
	0xfd, 0x19, 0xc7, 0xbf, 0x55, 0x20, 0x9d, 0xfe, 0x03, 0x5d, 0x8f, 0xb6, 0xa1, 0x11, 0x8e, 0x7b,
	0x07, 0xa9, 0x35, 0xc6, 0x1c, 0xd6, 0xd4, 0xc3, 0x71, 0x2f, 0xd9, 0xb5, 0xfe, 0xd0, 0x00, 0xcd,
	0x76, 0xd1, 0x53, 0x91, 0xd1, 0x4e, 0x10, 0x19, 0xf4, 0x10, 0x8c, 0xe7, 0x43, 0x42, 0xe3, 0x5c,
	0x58, 0xac, 0xc3, 0xfd, 0x74, 0x48, 0xa6, 0x62, 0x68, 0x2b, 0x12, 0xe9, 0x7f, 0xe2, 0x87, 0x64,
	0x8e, 0xc2, 0x2a, 0x61, 0xd6, 0xf7, 0x1a, 0xa0, 0x59, 0x6e, 0x74, 0x0f, 0x6a, 0x69, 0x81, 0x2b,
	0x6f, 0x6c, 0x86, 0x95, 0xf1, 0x8d, 0x3a, 0xbc, 0xf2, 0xb9, 0x43, 0xe1, 0xac, 0x3d, 0x68, 0xe4,
	0xc7, 0x8e, 0x39, 0xdf, 0xd5, 0x4a, 0x5e, 0x8d, 0x46, 0xc2, 0xfd, 0x93, 0x06, 0xf5, 0x5c, 0x8f,
	0x7f, 0xd2, 0x3a, 0xb7, 0x77, 0x5c, 0xc3, 0xf4, 0x5e, 0xf1, 0x49, 0x63, 0x2a, 0xbe, 0x13, 0xd5,
	0xe6, 0x73, 0xb8, 0x70, 0xcc, 0x19, 0x74, 0x05, 0x6a, 0xae, 0xc7, 0x89, 0x93, 0xc6, 0xa9, 0x69,
	0x67, 0x1b, 0xa7, 0x99, 0x4d, 0x9e, 0x41, 0x2d, 0x9d, 0xd7, 0x4e, 0xb5, 0x41, 0xb1, 0x7a, 0x80,
	0x66, 0xc7, 0x37, 0xd9, 0x78, 0xb3, 0x7e, 0x3f, 0x24, 0x51, 0xd1, 0x32, 0xec, 0x78, 0x95, 0x86,
	0x5f, 0x2f, 0x13, 0x7e, 0xeb, 0x19, 0x9c, 0x9b, 0x1e, 0xbf, 0xd0, 0x16, 0x18, 0x9c, 0x3d, 0x4f,
	0xb4, 0x2f, 0x36, 0x10, 0x66, 0x0a, 0x86, 0xb6, 0x42, 0x5b, 0x7b, 0x50, 0xcf, 0x6d, 0x9e, 0xae,
	0x67, 0xfe, 0x03, 0xcd, 0x89, 0x01, 0x4f, 0xde, 0x62, 0x8f, 0xba, 0xe4, 0x45, 0x1c, 0xe9, 0x68,
	0x61, 0x7d, 0xa7, 0x41, 0x23, 0x3f, 0xb5, 0x9d, 0xf4, 0x1a, 0x9f, 0x66, 0xdf, 0x6f, 0x7d, 0x0c,
	0x60, 0x13, 0x87, 0x71, 0x57, 0x69, 0xd6, 0x85, 0xa5, 0xe8, 0xbf, 0xbd, 0x39, 0x5c, 0x93, 0x20,
	0x2d, 0x17, 0x9a, 0x13, 0x23, 0xa5, 0x74, 0x4b, 0x80, 0xb9, 0x88, 0x38, 0x6b, 0x76, 0xb4, 0x48,
	0x07, 0x31, 0x7d, 0xae, 0x41, 0xcc, 0xda, 0x84, 0x5a, 0x3a, 0x68, 0xce, 0x97, 0x74, 0x3a, 0x2f,
	0x75, 0xb8, 0xee, 0xb0, 0x51, 0x11, 0xc9, 0x9d, 0xda, 0x8e, 0x8f, 0xe9, 0x0e, 0x67, 0x82, 0xed,
	0x68, 0x7b, 0xff, 0x1f, 0x78, 0x62, 0x38, 0x96, 0xc7, 0x46, 0x6b, 0x19, 0x78, 0x2d, 0x06, 0xe3,
	0xc0, 0x5b, 0xcb, 0xfe, 0x3d, 0xfe, 0x41, 0x37, 0xba, 0x8f, 0xba, 0x3b, 0x3f, 0xeb, 0xd7, 0xba,
	0x99, 0x98, 0x47, 0xd1, 0xc9, 0x6e, 0x2a, 0x46, 0xb2, 0xb7, 0x76, 0xd7, 0x7f, 0xcd, 0x9f, 0xda,
	0x8f, 0x4e, 0xed, 0xa7, 0xa7, 0xf6, 0xe5, 0xa9, 0xfd, 0xdd, 0xf5, 0xd7, 0xfa, 0x5a, 0x81, 0x53,
	0xfb, 0xf7, 0x76, 0x3a, 0x8f, 0x89, 0xc0, 0x2e, 0x16, 0xf8, 0x77, 0xfd, 0x7a, 0x86, 0x68, 0xb7,
	0x23, 0x48, 0xbb, 0x9d, 0x62, 0xda, 0x6d, 0x09, 0x6a, 0xb7, 0x77, 0xd7, 0x7b, 0x15, 0xa5, 0xfa,
	0xcd, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xba, 0x81, 0x07, 0x2b, 0x01, 0x17, 0x00, 0x00,
}
