// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/kit/node/node.proto

package node

import (
	fmt "fmt"
	types "github.com/cloudproud/lunodb.pb/proto/kit/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type OperatorStatement int32

const (
	OperatorUnknown    OperatorStatement = 0
	Where              OperatorStatement = 1
	Limit              OperatorStatement = 2
	Offset             OperatorStatement = 3
	Order              OperatorStatement = 4
	LeftJoin           OperatorStatement = 5
	RightJoin          OperatorStatement = 6
	InnerJoin          OperatorStatement = 7
	OuterJoin          OperatorStatement = 8
	Equal              OperatorStatement = 9
	NotEqual           OperatorStatement = 10
	In                 OperatorStatement = 11
	NotIn              OperatorStatement = 12
	GreaterThan        OperatorStatement = 13
	GreaterOrEqualThan OperatorStatement = 14
	LessThan           OperatorStatement = 15
	LessOrEqualThan    OperatorStatement = 16
	Like               OperatorStatement = 17
	NotLike            OperatorStatement = 18
	ILike              OperatorStatement = 19
	NotILike           OperatorStatement = 20
	RegMatch           OperatorStatement = 21
	NotRegMatch        OperatorStatement = 22
	RegIMatch          OperatorStatement = 23
	NotRegIMatch       OperatorStatement = 24
	IsDistinctFrom     OperatorStatement = 25
	IsNotDistinctFrom  OperatorStatement = 26
	Any                OperatorStatement = 27
	All                OperatorStatement = 28
	Binary             OperatorStatement = 29
)

var OperatorStatement_name = map[int32]string{
	0:  "OperatorUnknown",
	1:  "Where",
	2:  "Limit",
	3:  "Offset",
	4:  "Order",
	5:  "LeftJoin",
	6:  "RightJoin",
	7:  "InnerJoin",
	8:  "OuterJoin",
	9:  "Equal",
	10: "NotEqual",
	11: "In",
	12: "NotIn",
	13: "GreaterThan",
	14: "GreaterOrEqualThan",
	15: "LessThan",
	16: "LessOrEqualThan",
	17: "Like",
	18: "NotLike",
	19: "ILike",
	20: "NotILike",
	21: "RegMatch",
	22: "NotRegMatch",
	23: "RegIMatch",
	24: "NotRegIMatch",
	25: "IsDistinctFrom",
	26: "IsNotDistinctFrom",
	27: "Any",
	28: "All",
	29: "Binary",
}

var OperatorStatement_value = map[string]int32{
	"OperatorUnknown":    0,
	"Where":              1,
	"Limit":              2,
	"Offset":             3,
	"Order":              4,
	"LeftJoin":           5,
	"RightJoin":          6,
	"InnerJoin":          7,
	"OuterJoin":          8,
	"Equal":              9,
	"NotEqual":           10,
	"In":                 11,
	"NotIn":              12,
	"GreaterThan":        13,
	"GreaterOrEqualThan": 14,
	"LessThan":           15,
	"LessOrEqualThan":    16,
	"Like":               17,
	"NotLike":            18,
	"ILike":              19,
	"NotILike":           20,
	"RegMatch":           21,
	"NotRegMatch":        22,
	"RegIMatch":          23,
	"NotRegIMatch":       24,
	"IsDistinctFrom":     25,
	"IsNotDistinctFrom":  26,
	"Any":                27,
	"All":                28,
	"Binary":             29,
}

func (x OperatorStatement) String() string {
	return proto.EnumName(OperatorStatement_name, int32(x))
}

func (OperatorStatement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{0}
}

type ComparisonType int32

const (
	UnknownComparisonType ComparisonType = 0
	VariableConstant      ComparisonType = 1
	VariableVariable      ComparisonType = 2
)

var ComparisonType_name = map[int32]string{
	0: "UnknownComparisonType",
	1: "VariableConstant",
	2: "VariableVariable",
}

var ComparisonType_value = map[string]int32{
	"UnknownComparisonType": 0,
	"VariableConstant":      1,
	"VariableVariable":      2,
}

func (x ComparisonType) String() string {
	return proto.EnumName(ComparisonType_name, int32(x))
}

func (ComparisonType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{1}
}

type BinaryStatement int32

const (
	BinaryStatementUnknown BinaryStatement = 0
	Bitand                 BinaryStatement = 1
	Bitor                  BinaryStatement = 2
	Bitxor                 BinaryStatement = 3
	Plus                   BinaryStatement = 4
	Minus                  BinaryStatement = 5
	Mult                   BinaryStatement = 6
	Div                    BinaryStatement = 7
	FloorDiv               BinaryStatement = 8
	Mod                    BinaryStatement = 9
	Concat                 BinaryStatement = 10
	LShift                 BinaryStatement = 11
	RShift                 BinaryStatement = 12
	Pow                    BinaryStatement = 13
	JSONFetchText          BinaryStatement = 14
	JSONFetchVal           BinaryStatement = 15
)

var BinaryStatement_name = map[int32]string{
	0:  "BinaryStatementUnknown",
	1:  "Bitand",
	2:  "Bitor",
	3:  "Bitxor",
	4:  "Plus",
	5:  "Minus",
	6:  "Mult",
	7:  "Div",
	8:  "FloorDiv",
	9:  "Mod",
	10: "Concat",
	11: "LShift",
	12: "RShift",
	13: "Pow",
	14: "JSONFetchText",
	15: "JSONFetchVal",
}

var BinaryStatement_value = map[string]int32{
	"BinaryStatementUnknown": 0,
	"Bitand":                 1,
	"Bitor":                  2,
	"Bitxor":                 3,
	"Plus":                   4,
	"Minus":                  5,
	"Mult":                   6,
	"Div":                    7,
	"FloorDiv":               8,
	"Mod":                    9,
	"Concat":                 10,
	"LShift":                 11,
	"RShift":                 12,
	"Pow":                    13,
	"JSONFetchText":          14,
	"JSONFetchVal":           15,
}

func (x BinaryStatement) String() string {
	return proto.EnumName(BinaryStatement_name, int32(x))
}

func (BinaryStatement) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{2}
}

type Operator struct {
	Statement            OperatorStatement `protobuf:"varint,1,opt,name=statement,proto3,enum=cloudproud.lunodb.kit.node.v1.OperatorStatement" json:"statement,omitempty"`
	ComparisonTypes      []ComparisonType  `protobuf:"varint,2,rep,packed,name=comparison_types,json=comparisonTypes,proto3,enum=cloudproud.lunodb.kit.node.v1.ComparisonType" json:"comparison_types,omitempty"`
	Required             bool              `protobuf:"varint,3,opt,name=required,proto3" json:"required,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Operator) Reset()         { *m = Operator{} }
func (m *Operator) String() string { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()    {}
func (*Operator) Descriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{0}
}
func (m *Operator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operator.Unmarshal(m, b)
}
func (m *Operator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operator.Marshal(b, m, deterministic)
}
func (m *Operator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operator.Merge(m, src)
}
func (m *Operator) XXX_Size() int {
	return xxx_messageInfo_Operator.Size(m)
}
func (m *Operator) XXX_DiscardUnknown() {
	xxx_messageInfo_Operator.DiscardUnknown(m)
}

var xxx_messageInfo_Operator proto.InternalMessageInfo

func (m *Operator) GetStatement() OperatorStatement {
	if m != nil {
		return m.Statement
	}
	return OperatorUnknown
}

func (m *Operator) GetComparisonTypes() []ComparisonType {
	if m != nil {
		return m.ComparisonTypes
	}
	return nil
}

func (m *Operator) GetRequired() bool {
	if m != nil {
		return m.Required
	}
	return false
}

type Table struct {
	Name                 string      `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	Schema               string      `protobuf:"bytes,11,opt,name=schema,proto3" json:"schema,omitempty"`
	Catalog              string      `protobuf:"bytes,12,opt,name=catalog,proto3" json:"catalog,omitempty"`
	Schemaless           bool        `protobuf:"varint,13,opt,name=schemaless,proto3" json:"schemaless,omitempty"`
	Columns              []*Column   `protobuf:"bytes,14,rep,name=columns,proto3" json:"columns,omitempty"`
	Connector            string      `protobuf:"bytes,15,opt,name=connector,proto3" json:"connector,omitempty"`
	Operators            []*Operator `protobuf:"bytes,16,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}
func (*Table) Descriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{1}
}
func (m *Table) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Table.Unmarshal(m, b)
}
func (m *Table) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Table.Marshal(b, m, deterministic)
}
func (m *Table) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Table.Merge(m, src)
}
func (m *Table) XXX_Size() int {
	return xxx_messageInfo_Table.Size(m)
}
func (m *Table) XXX_DiscardUnknown() {
	xxx_messageInfo_Table.DiscardUnknown(m)
}

var xxx_messageInfo_Table proto.InternalMessageInfo

func (m *Table) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Table) GetSchema() string {
	if m != nil {
		return m.Schema
	}
	return ""
}

func (m *Table) GetCatalog() string {
	if m != nil {
		return m.Catalog
	}
	return ""
}

func (m *Table) GetSchemaless() bool {
	if m != nil {
		return m.Schemaless
	}
	return false
}

func (m *Table) GetColumns() []*Column {
	if m != nil {
		return m.Columns
	}
	return nil
}

func (m *Table) GetConnector() string {
	if m != nil {
		return m.Connector
	}
	return ""
}

func (m *Table) GetOperators() []*Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

type Catalog struct {
	UID                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Labels               []string `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty"`
	Tables               []*Table `protobuf:"bytes,6,rep,name=tables,proto3" json:"tables,omitempty"`
	Hidden               bool     `protobuf:"varint,7,opt,name=hidden,proto3" json:"hidden,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Catalog) Reset()         { *m = Catalog{} }
func (m *Catalog) String() string { return proto.CompactTextString(m) }
func (*Catalog) ProtoMessage()    {}
func (*Catalog) Descriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{2}
}
func (m *Catalog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Catalog.Unmarshal(m, b)
}
func (m *Catalog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Catalog.Marshal(b, m, deterministic)
}
func (m *Catalog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Catalog.Merge(m, src)
}
func (m *Catalog) XXX_Size() int {
	return xxx_messageInfo_Catalog.Size(m)
}
func (m *Catalog) XXX_DiscardUnknown() {
	xxx_messageInfo_Catalog.DiscardUnknown(m)
}

var xxx_messageInfo_Catalog proto.InternalMessageInfo

func (m *Catalog) GetUID() uint64 {
	if m != nil {
		return m.UID
	}
	return 0
}

func (m *Catalog) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Catalog) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Catalog) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Catalog) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Catalog) GetTables() []*Table {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *Catalog) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

type Column struct {
	Name                 string      `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *types.Type `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Indexed              bool        `protobuf:"varint,5,opt,name=indexed,proto3" json:"indexed,omitempty"`
	Nullable             bool        `protobuf:"varint,6,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Operators            []*Operator `protobuf:"bytes,7,rep,name=operators,proto3" json:"operators,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Column) Reset()         { *m = Column{} }
func (m *Column) String() string { return proto.CompactTextString(m) }
func (*Column) ProtoMessage()    {}
func (*Column) Descriptor() ([]byte, []int) {
	return fileDescriptor_92031d0e519ae2b4, []int{3}
}
func (m *Column) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Column.Unmarshal(m, b)
}
func (m *Column) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Column.Marshal(b, m, deterministic)
}
func (m *Column) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Column.Merge(m, src)
}
func (m *Column) XXX_Size() int {
	return xxx_messageInfo_Column.Size(m)
}
func (m *Column) XXX_DiscardUnknown() {
	xxx_messageInfo_Column.DiscardUnknown(m)
}

var xxx_messageInfo_Column proto.InternalMessageInfo

func (m *Column) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Column) GetType() *types.Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *Column) GetIndexed() bool {
	if m != nil {
		return m.Indexed
	}
	return false
}

func (m *Column) GetNullable() bool {
	if m != nil {
		return m.Nullable
	}
	return false
}

func (m *Column) GetOperators() []*Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

func init() {
	proto.RegisterEnum("cloudproud.lunodb.kit.node.v1.OperatorStatement", OperatorStatement_name, OperatorStatement_value)
	proto.RegisterEnum("cloudproud.lunodb.kit.node.v1.ComparisonType", ComparisonType_name, ComparisonType_value)
	proto.RegisterEnum("cloudproud.lunodb.kit.node.v1.BinaryStatement", BinaryStatement_name, BinaryStatement_value)
	proto.RegisterType((*Operator)(nil), "cloudproud.lunodb.kit.node.v1.Operator")
	proto.RegisterType((*Table)(nil), "cloudproud.lunodb.kit.node.v1.Table")
	proto.RegisterType((*Catalog)(nil), "cloudproud.lunodb.kit.node.v1.Catalog")
	proto.RegisterType((*Column)(nil), "cloudproud.lunodb.kit.node.v1.Column")
}

func init() { proto.RegisterFile("proto/kit/node/node.proto", fileDescriptor_92031d0e519ae2b4) }

var fileDescriptor_92031d0e519ae2b4 = []byte{
	// 1062 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x4b, 0x6f, 0x1b, 0x45,
	0x1c, 0xef, 0xfa, 0xed, 0xbf, 0x13, 0x7b, 0x32, 0x6d, 0xc2, 0xc6, 0x6d, 0x5a, 0x37, 0x02, 0x11,
	0x2a, 0x61, 0x93, 0x70, 0x41, 0x16, 0x12, 0xc2, 0x4e, 0x53, 0xb9, 0x71, 0xec, 0xc8, 0x49, 0x03,
	0x42, 0x41, 0x68, 0xbc, 0x3b, 0xb1, 0x47, 0xd9, 0x9d, 0x71, 0x77, 0x66, 0xdb, 0xe4, 0x1b, 0x70,
	0xe7, 0x1b, 0xc0, 0x8d, 0x2f, 0x82, 0xc4, 0x09, 0x89, 0x3b, 0x87, 0x1e, 0x40, 0xe2, 0x0b, 0x70,
	0x45, 0x33, 0xb3, 0x7e, 0xf1, 0x48, 0x10, 0x97, 0xf5, 0xff, 0xf7, 0xfb, 0xbf, 0x1f, 0xeb, 0x85,
	0xcd, 0x49, 0x24, 0x94, 0x68, 0x5c, 0x32, 0xd5, 0xe0, 0xc2, 0xa7, 0xe6, 0x51, 0x37, 0x1c, 0xde,
	0xf2, 0x02, 0x11, 0xfb, 0x93, 0x48, 0xc4, 0x7e, 0x3d, 0x88, 0xb9, 0xf0, 0x87, 0xf5, 0x4b, 0xa6,
	0xea, 0xc6, 0xe2, 0xd5, 0x6e, 0xf5, 0xde, 0x48, 0x8c, 0x84, 0xf5, 0xd6, 0x92, 0x75, 0xaa, 0x3e,
	0x1a, 0x09, 0x31, 0x0a, 0x68, 0xc3, 0xa0, 0x61, 0x7c, 0xd1, 0x50, 0x2c, 0xa4, 0x52, 0x91, 0x70,
	0x92, 0x18, 0xdc, 0x9f, 0x27, 0x54, 0xd7, 0x13, 0x2a, 0xed, 0xd3, 0x2a, 0xb7, 0x7f, 0x72, 0xa0,
	0xd0, 0x9f, 0xd0, 0x88, 0x28, 0x11, 0xe1, 0x1e, 0x14, 0xa5, 0x22, 0x8a, 0x86, 0x94, 0x2b, 0xd7,
	0xa9, 0x39, 0x3b, 0xe5, 0xbd, 0x0f, 0xea, 0x37, 0xd6, 0x54, 0x9f, 0xfa, 0x9e, 0x4c, 0xfd, 0x06,
	0xf3, 0x10, 0xf8, 0x73, 0x40, 0x9e, 0x08, 0x27, 0x24, 0x62, 0x52, 0xf0, 0xaf, 0x4c, 0x5a, 0x37,
	0x55, 0x4b, 0xef, 0x94, 0xf7, 0xde, 0xbf, 0x25, 0x6c, 0x7b, 0xe6, 0x76, 0x7a, 0x3d, 0xa1, 0x83,
	0x8a, 0xb7, 0x84, 0x25, 0xae, 0x42, 0x21, 0xa2, 0x2f, 0x63, 0x16, 0x51, 0xdf, 0x4d, 0xd7, 0x9c,
	0x9d, 0xc2, 0x60, 0x86, 0xb7, 0xbf, 0x49, 0x41, 0xf6, 0x94, 0x0c, 0x03, 0x8a, 0x31, 0x64, 0x38,
	0x09, 0xa9, 0x0b, 0x35, 0x67, 0xa7, 0x38, 0x30, 0x32, 0xde, 0x80, 0x9c, 0xf4, 0xc6, 0x34, 0x24,
	0x6e, 0xc9, 0xb0, 0x09, 0xc2, 0x2e, 0xe4, 0x3d, 0xa2, 0x48, 0x20, 0x46, 0xee, 0x8a, 0x51, 0x4c,
	0x21, 0x7e, 0x08, 0x60, 0x6d, 0x02, 0x2a, 0xa5, 0xbb, 0x6a, 0xb2, 0x2d, 0x30, 0xf8, 0x13, 0xc8,
	0x7b, 0x22, 0x88, 0x43, 0x2e, 0xdd, 0x72, 0x2d, 0xbd, 0x53, 0xda, 0x7b, 0xe7, 0xd6, 0xe6, 0xb4,
	0xf5, 0x60, 0xea, 0x85, 0x1f, 0x40, 0xd1, 0x13, 0x9c, 0x53, 0x4f, 0x89, 0xc8, 0xad, 0x98, 0xe4,
	0x73, 0x02, 0x3f, 0x85, 0xa2, 0x48, 0x86, 0x2c, 0x5d, 0x64, 0x12, 0xbc, 0xfb, 0x1f, 0x97, 0x32,
	0x98, 0x7b, 0x6e, 0xff, 0xea, 0x40, 0xbe, 0x9d, 0x74, 0xb4, 0x09, 0xe9, 0x98, 0xf9, 0x66, 0xc3,
	0x99, 0x56, 0xfe, 0xcd, 0x2f, 0x8f, 0xd2, 0x2f, 0x3a, 0xfb, 0x03, 0xcd, 0xe9, 0x5a, 0xf4, 0x98,
	0xe4, 0x84, 0x78, 0xd4, 0x4d, 0xd9, 0x5a, 0x66, 0xc4, 0x6c, 0xa0, 0xe9, 0x85, 0x81, 0xd6, 0xa0,
	0xe4, 0x53, 0xe9, 0x45, 0x6c, 0xa2, 0x98, 0xe0, 0x6e, 0xc6, 0xa8, 0x16, 0x29, 0x3d, 0xf2, 0x80,
	0x0c, 0x69, 0x20, 0xdd, 0x6c, 0x2d, 0xad, 0x47, 0x6e, 0x11, 0xfe, 0x18, 0x72, 0x4a, 0xef, 0x49,
	0xba, 0x39, 0xd3, 0xd6, 0xdb, 0xb7, 0xb4, 0x65, 0x96, 0x3a, 0x48, 0x7c, 0x74, 0xd4, 0x31, 0xf3,
	0x7d, 0xca, 0xdd, 0xbc, 0x59, 0x49, 0x82, 0xb6, 0x7f, 0x76, 0x20, 0x67, 0x27, 0xfc, 0x8f, 0xe5,
	0x7e, 0x04, 0x19, 0x7d, 0x88, 0xa6, 0xce, 0x7f, 0x4f, 0x69, 0x5f, 0x11, 0x9d, 0x53, 0x9f, 0x9f,
	0xf1, 0xd0, 0x17, 0xc2, 0xb8, 0x4f, 0xaf, 0xa8, 0xef, 0x66, 0x4d, 0xc6, 0x29, 0xd4, 0xd7, 0xc8,
	0xe3, 0x20, 0xd0, 0x75, 0xb9, 0x39, 0x7b, 0x8d, 0x53, 0xbc, 0xbc, 0xbe, 0xfc, 0xff, 0x5d, 0xdf,
	0x93, 0x1f, 0xd2, 0xb0, 0xf6, 0xb7, 0x77, 0x0d, 0xdf, 0x85, 0xca, 0x94, 0x7c, 0xc1, 0x2f, 0xb9,
	0x78, 0xcd, 0xd1, 0x1d, 0x5c, 0x84, 0xec, 0x67, 0x63, 0x1a, 0x51, 0xe4, 0x68, 0xb1, 0xcb, 0x42,
	0xa6, 0x50, 0x0a, 0x03, 0xe4, 0xfa, 0x17, 0x17, 0x92, 0x2a, 0x94, 0xd6, 0x74, 0x3f, 0xf2, 0x69,
	0x84, 0x32, 0x78, 0x05, 0x0a, 0x5d, 0x7a, 0xa1, 0x9e, 0x0b, 0xc6, 0x51, 0x16, 0xaf, 0x42, 0x71,
	0xc0, 0x46, 0x63, 0x0b, 0x73, 0x1a, 0x76, 0x38, 0xa7, 0x91, 0x81, 0x79, 0x0d, 0xfb, 0xb1, 0x4a,
	0x60, 0x41, 0x47, 0x79, 0xfa, 0x32, 0x26, 0x01, 0x2a, 0xea, 0x28, 0x3d, 0xa1, 0x2c, 0x02, 0x9c,
	0x83, 0x54, 0x87, 0xa3, 0x92, 0x36, 0xe8, 0x09, 0xd5, 0xe1, 0x68, 0x05, 0x57, 0xa0, 0xf4, 0x2c,
	0xa2, 0x44, 0xd1, 0xe8, 0x74, 0x4c, 0x38, 0x5a, 0xc5, 0x1b, 0x80, 0x13, 0xa2, 0x1f, 0x19, 0x3f,
	0xc3, 0x97, 0x6d, 0x3d, 0x52, 0x1a, 0x54, 0xd1, 0xfd, 0x69, 0xb4, 0x68, 0x82, 0x70, 0x01, 0x32,
	0x5d, 0x76, 0x49, 0xd1, 0x1a, 0x2e, 0x41, 0xbe, 0x27, 0x94, 0x01, 0x58, 0x67, 0xeb, 0x18, 0xf1,
	0x6e, 0x52, 0x8e, 0x45, 0xf7, 0x34, 0x1a, 0xd0, 0xd1, 0x11, 0x51, 0xde, 0x18, 0xad, 0xeb, 0x4a,
	0x7a, 0x42, 0xcd, 0x88, 0x0d, 0xd3, 0x33, 0x1d, 0x75, 0x2c, 0x7c, 0x0b, 0x23, 0x58, 0xb1, 0xfa,
	0x84, 0x71, 0x31, 0x86, 0x72, 0x47, 0xee, 0x33, 0xa9, 0x18, 0xf7, 0xd4, 0x41, 0x24, 0x42, 0xb4,
	0x89, 0xd7, 0x61, 0xad, 0x23, 0x7b, 0x42, 0x2d, 0xd1, 0x55, 0x9c, 0x87, 0xf4, 0xa7, 0xfc, 0x1a,
	0xdd, 0x37, 0x42, 0x10, 0xa0, 0x07, 0x7a, 0xec, 0x2d, 0xc6, 0x49, 0x74, 0x8d, 0xb6, 0xaa, 0x99,
	0xaf, 0xbf, 0x7b, 0x78, 0xe7, 0xc9, 0x97, 0x50, 0x5e, 0xfe, 0x77, 0xc3, 0x9b, 0xb0, 0x9e, 0x6c,
	0x6f, 0x59, 0x81, 0xee, 0xe0, 0x7b, 0x80, 0xce, 0x48, 0xc4, 0xf4, 0x25, 0xb5, 0x05, 0x97, 0x8a,
	0x70, 0x85, 0x9c, 0x45, 0x76, 0xfa, 0x8b, 0x52, 0x49, 0xf8, 0xdf, 0x1c, 0xa8, 0xd8, 0x8c, 0xf3,
	0x33, 0xa9, 0xc2, 0xc6, 0x5f, 0xa8, 0xf9, 0xb5, 0x98, 0x02, 0x15, 0xe1, 0xbe, 0x3d, 0x97, 0x16,
	0x53, 0x22, 0xb2, 0xe7, 0xd2, 0x62, 0xea, 0x4a, 0x44, 0x28, 0xad, 0x07, 0x7e, 0x1c, 0xc4, 0x12,
	0x65, 0xb4, 0xc1, 0x11, 0xe3, 0xb1, 0x44, 0x59, 0x4d, 0x1e, 0xc5, 0x81, 0x42, 0x39, 0xdd, 0xeb,
	0x3e, 0x7b, 0x85, 0xf2, 0x7a, 0xd0, 0x07, 0x81, 0x10, 0x91, 0x46, 0x05, 0x4d, 0x1f, 0x09, 0x1f,
	0x15, 0x75, 0xa8, 0xb6, 0xe0, 0x1e, 0x51, 0x08, 0xb4, 0xdc, 0x3d, 0x19, 0xb3, 0x0b, 0x85, 0x4a,
	0x5a, 0x1e, 0x58, 0x79, 0x45, 0x1b, 0x1f, 0x8b, 0xd7, 0x68, 0x15, 0xaf, 0xc1, 0xea, 0xf3, 0x93,
	0x7e, 0xef, 0x80, 0x2a, 0x6f, 0x7c, 0x4a, 0xaf, 0x14, 0x2a, 0xeb, 0x8d, 0xcc, 0xa8, 0x33, 0x12,
	0xa0, 0x8a, 0xed, 0xb4, 0xf5, 0x87, 0x03, 0x8f, 0x3d, 0x11, 0xde, 0xfc, 0x32, 0xb5, 0x8a, 0x3d,
	0xe1, 0xd3, 0x63, 0xfd, 0xad, 0x3b, 0x76, 0xbe, 0xa8, 0x8f, 0x98, 0x1a, 0xc7, 0xc3, 0xba, 0x27,
	0xc2, 0xc6, 0xdc, 0xad, 0x91, 0xb8, 0x4d, 0x86, 0x8d, 0xe5, 0x6f, 0xf3, 0xb7, 0xa9, 0x4c, 0xbb,
	0x7b, 0xd8, 0xfb, 0x3e, 0xb5, 0xd5, 0x9e, 0xe7, 0xe8, 0x5a, 0xe3, 0x43, 0xa6, 0xea, 0x3a, 0x74,
	0xfd, 0x6c, 0xf7, 0xc7, 0x45, 0xfd, 0xb9, 0xd5, 0x9f, 0x1f, 0x32, 0x75, 0xae, 0xf5, 0xe7, 0x67,
	0xbb, 0x6f, 0x52, 0xef, 0xdd, 0xa8, 0x3f, 0x7f, 0x76, 0xdc, 0x3a, 0xa2, 0x8a, 0xf8, 0x44, 0x91,
	0xdf, 0x53, 0x8f, 0xe7, 0xb6, 0xcd, 0xa6, 0x35, 0x6e, 0x36, 0x0f, 0x99, 0x6a, 0x36, 0xb5, 0x79,
	0xb3, 0x79, 0xb6, 0x3b, 0xcc, 0x99, 0x32, 0x3f, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0x86, 0xc1,
	0xe7, 0x75, 0x4b, 0x08, 0x00, 0x00,
}
